### ISSUE TITLE
CUDA out of memory 오류

### ISSUE THREAD

**Issue by kohyoonchan** [wlsdml1114/diff-svc#10]
Skip item (CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 4.00 GiB total capacity; 1.96 GiB already allocated; 104.51 MiB free; 2.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF). item_name: data\test\0314-995-000.wav, wav_fn: data\test\0314-995-000.wav
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:50<00:00, 10.20s/it]
| valid total duration: 14.005s
  0%| 라고 오류가 뜨네요 max_sentences를 6으로 내려도 계속 뜹니다

**Comment by wlsdml1114** [comment]
GPU메모리가 부족해서 뜨는거에요
https://github.com/wlsdml1114/diff-svc/issues/5
위 내용 참고해보세요

**Comment by MoorDev** [comment]
config.yaml에서 use_crepe만 false로 해도 나아집니다.
infer할때 gpu대신 cpu사용하는것으로 해야 하고요.
