### ISSUE TITLE
저번에 램 작다는 오류로 댓글 단 코딩 하나도 모르는 일반인입니다.. 처음부터 다시 하는데 이번엔 이런 오류가 나옵니다.

### ISSUE THREAD

**Issue by seohyunp69** [wlsdml1114/diff-svc#11]
pip install -r requirements.txt 을 칠때
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall. 이렇게 뜨고,

python sep_wav.py 를(와 다른 것들도) 칠때는
import librosa
ModuleNotFoundError: No module named 'librosa' 이렇게 뜨네요..

**Comment by wlsdml1114** [comment]
처음에 pip install이 실패해서 그 뒤에 실행하는 파일들에서 라이브러리를 불러오는게 실패한거에요
pip install이 성공적으로 실행되어야 그 다음단계를 진행할 수 있습니다.

근데 이 프로젝트 requirement에는 llvmlite 관련된 라이브러리가 없을텐데.. 왜 저 에러가 뜨는지 모르겠네요

**Comment by seohyunp69** [comment]
저 그럼 pip install이 실패하는 이유는 뭘까여..?ㅠㅠ
요구사항이 이미 충족됬다고 그러는데.. 혹시 처음부터 계속 다시해서 그런가여?

**Comment by wlsdml1114** [comment]
가상환경을 지웠다가 다시한번 깔아보실래요?
저는 문제없이 설치가 잘되서..
```conda env remove -n diff-svc```
하면 지울 수 있습니다.

**Comment by MoorDev** [comment]
제가 최근에 한 실수인데
아나콘다에 env만들고 activate 안해서 librosa 등의 라이브러리 오류가 났었습니다.

혹시 activate 하고 시도하시는 것이 맞나요?
새 powershell(혹은 cmd, termianl 등)을 열고 conda activate diff-svc 하셨나요?
새 쉘을 열게 되면 activate 하기 전까지 base에서 작업하기 때문에 잊어버리고 작업 하기도 합니다.

그리고 정 안 된다 싶으면 
pip install --ignore-installed -r requirement.txt 
이렇게해서 기존 설치를 무시하고 재설치 할 수도 있습니다.
