### ISSUE TITLE
학습을 ctrl+c로 종료후에 ckpt파일 생성이 안됩니다.

### ISSUE THREAD

**Issue by Honeish** [wlsdml1114/diff-svc#13]
테스트만 해볼려고 30분 정도만 학습하다가 ctrl+c로 학습 종료를 했는데 ckpt파일이 생성이 안되는데 
왜그런지 알수있을까요?

**Comment by wlsdml1114** [comment]
기본 세팅상 2000step이 지나야 파일이 생성되는데, 아마 2000파일이 되기 전에 학습을 종료하신게 아닌가 싶습니다.

**Comment by Honeish** [comment]
넵 2000스텝 후에 파일 생성되는거 확인했습니다.
감사합니다!
