### ISSUE TITLE
실패후 다시 도전

### ISSUE THREAD

**Issue by thuglife114** [wlsdml1114/diff-svc#14]
다 해서 결과를 얻기 했는데, 맘에 들지 않고, 기계음도 나고 해서

샘플 원본을 더 디테일하게 준비해서 다시 하려 합니다

이렇게 새로 시작하려는 경우

잘라서 옮겨논 audio파일과 ckpt 스텝 파일들 지우고

다시하면 될까요?

아니면 [diff-svc-main] 폴더를 다 삭제후 다시깔고 해야할까요?

**Comment by MoorDev** [comment]
audio와 ckpt만 지워도 다시 시작 하실 수 있습니다.

**Comment by thuglife114** [comment]
감사합니다

**Comment by wlsdml1114** [comment]
> audio와 ckpt만 지워도 다시 시작 하실 수 있습니다.

@MoorDev 
항상 도움 주셔서 감사합니다.
