### ISSUE TITLE
학습 중에 컴퓨터가 꺼져요

### ISSUE THREAD

**Issue by seohyunp69** [wlsdml1114/diff-svc#15]
(결과 이상한거 알고보니 학습이 덜 되어있었던거였네여..)
~분 경과하면 끄기/절전모드 설정도 없음으로 했는데 어제 학습시켜놓고 오늘 와보니 도중에 컴퓨터가 꺼져(사실상 다시 시작한건지 전원 자체는 켜져 있는데 초기화되어있고, 학습이 덜 되어있었음) 있었어요.. 혹시 메모리 이런거랑 관련이 있을까여?

**Comment by wlsdml1114** [comment]
보통 메모리가 부족하면 컴이 꺼지기보다 프로세스가 죽어버려서 학습 프로그램 자체랑은 직접적으로 연관은 없어보입니다.
다만 온도가 너무 높아지는거에 비해 쿨링성능이 부족하면 컴이 죽어버릴수 있습니다

**Comment by seohyunp69** [comment]
아하.. 뭔가 저장은 되는지 다시 실행하면 이어서 학습되긴 하네여
그럼 Epoch 뒤에 숫자가 얼마정도 나와야 충분히 학습이 된 건가요?
영상에선 1000얼마정도에서 끝났는데 저는 2300이 넘게 계속 하고 있어서요..

**Comment by MoorDev** [comment]
학습량은 데이터수에 따라 많이 다릅니다. 저의 경우 220000스텝 넘게 학습했으나 데이터 부족으로 인해 문제가 생겨 삭제했습니다.
그리고 컴퓨터가 꺼지는 것은 Windows의 경우 전원관리에 들어가서 자동 절전모드 등을 모두 꺼주셔야 합니다.

그래도 꺼지는 경우가 있는데 이쪽분야에서 일하는 제 친구의 경우 이런 경우가 잦아서 OS를 리눅스로 갈아탔습니다. 리눅스에서 학습하는 것도 고려해볼 필요가 있습니다.

**Comment by wlsdml1114** [comment]
저는 예시로 조금만 돌렸던거구요. 보통은 윗분처럼 몇십만스텝씩 하는게 보통입니다.
(데이터가 많은 경우에)

**Comment by seohyunp69** [comment]
아하 꺼지는건 말씀하신대로 그냥 오류?같네여 24시간짜리 유튜브 동영상 틀어놓고 하니까 안꺼졌다는..ㅋㅋ 
그럼 학습이 충분히 완료되면 자동으로 종료되나여? 그리고 저번에 오류 났을 때 ds worker 값을 낮춰서 해보라고 하셨는데(낮추니까 이재 오류 안나요), 그 값에 따라 학습 속도도 영향을 받는 건지 궁금합니다.

**Comment by wlsdml1114** [comment]
자동으로 종료되지는 않습니다.
loss가 더이상 줄지않는거처럼 보이면 중단하시면됩니다.
worker가 낮으면 한번에 학습하는 양이 적어져서 그만큼 시간이 오래걸리긴 할거에요.

**Comment by seohyunp69** [comment]
아하, 그렇다면 loss를 어디서 확인할 수 있고 학습을 다른 모델들로 더 하고 싶다면 어떻게 해야 하는지 알려주실 수 있나여?

**Comment by wlsdml1114** [comment]
loss는 학습중에 total loss가 계속갱신되서 뜹니다 그거 확인하시면되용
다른 데이터로 하고싶으시면 경로랑 이런거 다르게해서 config를 2개 만들어서 하면될거에요 아마..? 
그건 제가 안해봐서 모르겠습니다.
경험이 있으신 분들이 다른분들이 알려주실거에요

**Comment by seohyunp69** [comment]
아 넵 알겠습니다. 그리고 정말 죄송한데, 컴퓨터가 자동으로 꺼지는게 아니라 그래픽카드가 과부하가 걸려서 재부팅되는거더라고요.. 혹시 출력에 재한을 두거나 해서 이를 막을 방법 없을까여..?

**Comment by popop098** [comment]
> 아 넵 알겠습니다. 그리고 정말 죄송한데, 컴퓨터가 자동으로 꺼지는게 아니라 그래픽카드가 과부하가 걸려서 재부팅되는거더라고요.. 혹시 출력에 재한을 두거나 해서 이를 막을 방법 없을까여..?

저같은 경우는 선풍기로 공기순환이 되게끔 하거나 에어컨을 켜서 온도를 일정하게 유지를 하고있습니다.
다만 특이점이 방음부스안에서 작업하다보니 온도가 쉽게 올라가는편이라 에어컨을 주로 쓰고있네요

또는 사용하시는 그래픽카드가 구형이거나 먼지등으로인해 열배출이 원활하지 않을수있으니 참고해보세요.

**Comment by MoorDev** [comment]
> 아 넵 알겠습니다. 그리고 정말 죄송한데, 컴퓨터가 자동으로 꺼지는게 아니라 그래픽카드가 과부하가 걸려서 재부팅되는거더라고요.. 혹시 출력에 재한을 두거나 해서 이를 막을 방법 없을까여..?

제 생각에 파워가 모자라는것 같습니다. 비트코인 채굴시 그래픽카드에 성능제한을 거는 것과 같은 이유인데 게임은 기껏해야 그래픽카드 연산성능을 순간적으로 많이 쓰는거지 계속 쓰는게 아니라서 일반적인 출력의 파워도 상관없습니다만 딥러닝은 지속적으로 100%출력을 쓰기에 파워의 지속적인 성능도 중요합니다.

그니까 게임은 단거리 달리기라면 이건 장거리달리기라서 지속적이면서 안정적으로 공급해주는 파워를 써야할 듯 합니다

사람입장에선 잠깐 뛰는건 심장에 크게 무리가 없지만 오래뛰면 심장에 무리가는것과 같다고 할까요?

**Comment by wlsdml1114** [comment]
GPU가 일정온도 이상으로 올라가면 쓰로틀링이 걸리기때문에 출력제한을 걸어서 일정온도 이상으로 올라가지 못하게 막습니다.
제가알기로 85도 근처에서는 출력 제한을 거는 것으로 알고있습니다.
컴퓨터가 꺼지는정도면 출력제한 온도를 낮추시거나 윗분들 말씀대로 시원한 환경에 두시거나 파워(파워도 소모품입니다)를 바꾸시거나 청소를한번 해주셔야 할거 같습니다.
