### ISSUE TITLE
보이스 추출할 때 오류가 나옵니다.

### ISSUE THREAD

**Issue by josbarkkk** [wlsdml1114/diff-svc#16]
(diff-svc) C:\diff-svc-main>python sep_wav.py
mp4 to wav 변환 작업 중...: 100%|████████████████████████████████████████████████████████████████| 2/2 [00:00<?, ?it/s]
노멀라이징 작업 중...: 100%|█████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.00it/s]
음원 자르는 중...: 100%|█████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  8.54it/s]
Sample rate: 44100
목소리 추출 중...:   0%|                                                                        | 0/79 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\diff-svc-main\sep_wav.py", line 284, in <module>
    main(
  File "C:\diff-svc-main\sep_wav.py", line 220, in main
    sources = extract_voice(
  File "C:\diff-svc-main\sep_wav.py", line 61, in extract_voice
    out = model.forward(chunk)
  File "C:\Users\1\anaconda3\envs\diff-svc\lib\site-packages\torchaudio\models\_hdemucs.py", line 542, in forward
    raise ValueError(
ValueError: The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.

음원자르기까지는 되는데 이후에 목소리 추출이 안되는데 저  HDemucs에 문제가 있는 것 같은데 초보라 잘 모르겠습니다

**Comment by MoorDev** [comment]
자른 음원에서 아무소리도 없는 파일이 있을 경우입니다. 목소리 추출을 하지 않고 바이너리화 하다보면 그냥 스킵되는 파일이 있는데 대부분은 목소리가 없거나 아무소리도 안 들리는 파일이더군요.

원 데이터에서 목소리가 없는 구간이 있을 경우 최대한 줄여주시기 바랍니다.

**Comment by wlsdml1114** [comment]
https://github.com/wlsdml1114/diff-svc/commit/1610b12a16dcdd3a2950919282e00830de256a02
방금 커밋해서 해결했습니다.
음원을 mono로 바꾸고 demucs를 적용하면 에러가 있네요.
demucs후에 mono로 변경하도록 바꿨습니다.

**Comment by wlsdml1114** [comment]
git pull로 최신버전 업데이트해주시면 됩니다
