### ISSUE TITLE
결과물 이상

### ISSUE THREAD

**Issue by kohyoonchan** [wlsdml1114/diff-svc#17]
배치사이즈 6에 lr0.0004로 20만스탭 학습했는데 결과물 고음이 너무 안되네요 lr을 낮춰서 처음부터 다시학습해야할까요?

**Comment by MoorDev** [comment]
학습 데이터가 어느정도 되나요
최소한 3시간~4시간 분량은되어야 하고 노래도 고음이 어느정도 있는 노래도 넣어주셔야 문제 없을 것으로 생각됩니다.

**Comment by wlsdml1114** [comment]
데이터셋의 품질에 따라 다릅니다.
loss가 아무리 낮다고해도 데이터셋 자체에 고음데이터가없으면 고음에서 좋은 결과를 얻기 힘듭니다.

**Comment by kohyoonchan** [comment]
4시간 분량 말하는 것만 학습시켜서 그렇네요 감사합니다
