### ISSUE TITLE
binarize 과정 중 CUDA 에러 문제 질문드립니다.

### ISSUE THREAD

**Issue by VIRTUALLEAGUE** [wlsdml1114/diff-svc#2]
python preprocessing/binarize.py --config training/config.yaml 명령어 사용 결과
ValueError: zero-size array to reduction operation maximum which has no identity 에러코드를 내뱉습니다.

또한 Skip item (Torch not compiled with CUDA enabled) 문구도 0% ~ 100%까지 계속 뜨는 상황인데 혹시 해결방법을 알 수 있을까요?

추가로 7950X 4090 환경에서 올려줄 수 있을만한 config.yaml 설정값들이 있을까요?

**Comment by Hyundai0** [comment]
똑같은 오류가 발생합니다

**Comment by VIRTUALLEAGUE** [comment]
> 똑같은 오류가 발생합니다
@Hyundai0 
pip uninstall torch
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

두 명령어를 통해 해결하기는 했습니다! 전해전해 들어서는 CPU 버전이 설치된 것 같다고 하네요. 확실하지는 않습니다.
