### ISSUE TITLE
기계음

### ISSUE THREAD

**Issue by thuglife114** [wlsdml1114/diff-svc#20]
한 차분한 여자의 목소리 1시간정도 준비하여 학습도 20만스텝이상 돌리고, 구동해봤지만,

비슷한 톤의 여자의 목소리는 잘 변환 됩니다만

샘플보단 톤이 높거나, 톤이 낮은 남자의 목소리를 변환해보려 하니, 되긴하는데, 기계음으로 나옵니다

여기서 질문, 원본 샘플 목소리를 다운 받을수 있는 곳이 있을까요?

그리고, 한 사람의 샘플 목소리가 아닌 두명이상의 목소리로 학습시켜도 될까요?

**Comment by popop098** [comment]
두명이상을 한번에 한다면 각각 모델링화는 안될겁니다.(그냥 한명의 목소리로 인식할듯)
기계음이 나는이유는 제가 생각하기로는 원 샘플이 해당 음역대까지  있지않아 학습을 하지못해 발생하는것으로 보입니다.

**Comment by wlsdml1114** [comment]
그렇게 학습하시면 원하시는 성능이 나오지 않으실거에요

**Comment by thuglife114** [comment]
> 두명이상을 한번에 한다면 각각 모델링화는 안될겁니다.(그냥 한명의 목소리로 인식할듯) 기계음이 나는이유는 제가 생각하기로는 원 샘플이 해당 음역대까지 있지않아 학습을 하지못해 발생하는것으로 보입니다.

음역대 골고루 분포된 샘플 구할곳은 없을까요?

**Comment by wlsdml1114** [comment]
원하시는 데이터가 있을지는 모르겠지만 AIhub에서 찾아보시는것도 하나의 방법입니다.
https://aihub.or.kr/
과기정통부랑 NIA에서 운영중인 인공지능학습용데이터 구축사이트입니다.

**Comment by thuglife114** [comment]
> 있을지는 모르겠지만 AIhub에서 찾아보시는것도

감사합니다
