### ISSUE TITLE
학습 중 학습용 데이터 추가???

### ISSUE THREAD

**Issue by LEELEE412** [wlsdml1114/diff-svc#24]
지금 현재 15분 분량 정도로 학습을 진행하고 있는데 추후에 데이터를 더 모으게 되면 새로 학습을 진행해야 하나요?
아니면 데이터 파일에 다시 넣어두고 그대로 학습을 진행해도 되나요?

**Comment by MoorDev** [comment]
그대로 이어서 학습을 하시면 데이터 추가가 정상적으로 이루어 집니다.
--reset 옵션을 넣으면 새로 학습하는 것이고 그냥 하면 지금까지 만들어진 모델에 전이학습하는 개념으로 들어갑니다

**Comment by wlsdml1114** [comment]
각자 장단점이 있다고 생각하지만, 저는 보통 새로운데이터가 추가되면 전체 데이터로 처음부터 학습합니다

**Comment by LEELEE412** [comment]
> 

그게 더나은가요??? 저는 학습된 상태에 새로 넣는게 더 좋다고 봐서요

**Comment by LEELEE412** [comment]
> 그대로 이어서 학습을 하시면 데이터 추가가 정상적으로 이루어 집니다. --reset 옵션을 넣으면 새로 학습하는 것이고 그냥 하면 지금까지 만들어진 모델에 전이학습하는 개념으로 들어갑니다

감사합니다.

**Comment by JinEui-Kim** [comment]
> > 
> 
> 그게 더나은가요??? 저는 학습된 상태에 새로 넣는게 더 좋다고 봐서요

새로운 데이터의 퀄리티가 월등하게 좋다면 learning rate를 낮게 주고 transfer learning으로 새로운 데이터에 대해서만 학습하는게 좋지만
데이터의 퀄리티가 비슷하다면 오히려 새로운 데이터에 대해서만 학습하는것이 더 성능이 안 좋을 수 있습니다.
데이터에 따라 다르기 때문에 시간이 많으시면 둘 다 해보시는걸 추천드립니다.

**Comment by wlsdml1114** [comment]
> > 
> 
> 그게 더나은가요??? 저는 학습된 상태에 새로 넣는게 더 좋다고 봐서요

새로 추가된 데이터가 퀄리티가 월등하게 좋다면 그게 맞습니다.
learning rate를 기존보다 낮게 하고 새로 학습하면 그게 더 좋을 수 있습니다.
그게 아니라 비슷한 퀄리티면 전체를 다 학습하는게 좋습니다.
일반화된 목소리 특징을 얻을 수 있기 때문입니다.
말씀드린거처럼 각각의 장점이 있기 때문에 시간이 많으시면 둘 다 테스트해보시는것도 좋을것 같네요.
