### ISSUE TITLE
결과물 출력 단계 NameError: name 'false' is not defined. Did you mean: 'False'? 오류

### ISSUE THREAD

**Issue by wnsvy1113** [wlsdml1114/diff-svc#27]
(diff-svc) C:\Users\wnsvy\Desktop\diff-svc-main>python infer.py
C:\Users\wnsvy\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  File "C:\Users\wnsvy\Desktop\diff-svc-main\infer.py", line 9, in <module>
    from infer_tools import infer_tool
  File "C:\Users\wnsvy\Desktop\diff-svc-main\infer_tools\infer_tool.py", line 103, in <module>
    class Svc:
  File "C:\Users\wnsvy\Desktop\diff-svc-main\infer_tools\infer_tool.py", line 141, in Svc
    def infer(self, in_path, key, acc, use_pe=True, use_crepe=false, thre=0.05, singer=False, **kwargs):
NameError: name 'false' is not defined. Did you mean: 'False'?

이렇게 나옵니다..
어떻게 해야하나요? 말 그대로 이름 오류인가요?

**Comment by popop098** [comment]
`use_crepe=false`에서 `false` --> `False`로 수정하시면 될듯합니다.

**Comment by wnsvy1113** [comment]
수정했더니 이번엔 test가 없다고 뜹니다.
(diff-svc) C:\Users\wnsvy\Desktop\diff-svc-main>python infer.py
C:\Users\wnsvy\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
| load 'model' from './checkpoints/test/model_ckpt_steps_246000.ckpt'.
| load 'model' from 'checkpoints/0102_xiaoma_pe/model_ckpt_steps_60000.ckpt'.
| load HifiGAN:  checkpoints/0109_hifigan_bigpopcs_hop128\model_ckpt_steps_1512000.ckpt
Removing weight norm...
| Loaded model parameters from checkpoints/0109_hifigan_bigpopcs_hop128\model_ckpt_steps_1512000.ckpt.
| HifiGAN device: cuda.
Traceback (most recent call last):
  File "C:\Users\wnsvy\Desktop\diff-svc-main\infer.py", line 103, in <module>
    add_noise_step=500, f_name=f_name, project_name=test, format=format)
NameError: name 'test' is not defined

**Comment by popop098** [comment]
> project_name=test

`project_name=test`을 `project_name="test"`로 수정하세요

**Comment by wnsvy1113** [comment]
와 진짜 감사합니다 덕분에 결과물 잘뽑았습니다👍
