### ISSUE TITLE
학습코드 실행 과정에서 문제가 발생합니다

### ISSUE THREAD

**Issue by hjklfds** [wlsdml1114/diff-svc#3]
AssertionError: Torch not compiled with CUDA enabled 의 오류가 나옵니다.
그리고 반드시 엔비디아 GPU로만 사용해야되나요?
가지고있는 GPU 중에선 라데온 GPU 성능이 더 높아서 사용하고 싶은데 CUDA가 엔비디아 인걸 보고 여쭈어 봅니다.

**Comment by wlsdml1114** [comment]
아마 cuda만 가능한거로 알고 있습니다.
라데온환경에서는 테스트 안해봤습니다.
말씀하신 오류는 오늘 업데이트한 "README - 환습환경 세팅 - library 설치"를 참고해주세요
pytorch 2.0이 나와서 버전 에러때문에 발생한 것으로 보입니다.

**Comment by MoorDev** [comment]
ROCM 버전의  pytorch를 설치하고 시도해보세요. 다만 ROCM은 리눅스에서만 가능합니다. (23년현재 우분투 20.04나 22.04추천)
https://pytorch.org/get-started/previous-versions/
여기에 가니 

```
pip3 install torch torchvision torchaudio --extra-index-url
pip install torch==1.13.1+rocm5.2 torchvision==0.14.1+rocm5.2 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/rocm5.2
```

이렇게 하면 rocm버전 pytorch가 설치된다고 합니다.

라이브러리 설치할 때 기존 pytorch를 지우고 이 버전을 설치하면 될 듯 합니다.
