### ISSUE TITLE
결과물 파일 확장자변경

### ISSUE THREAD

**Issue by popop098** [wlsdml1114/diff-svc#31]
https://github.com/wlsdml1114/diff-svc/blob/902e40d0e1a0e94429a19933f8787301fbc8d360/infer.py#L91
이 부분에 mp3로 하니 에러가 발생하던데 혹시 변경이 불가한것일까요?
현재 외출한 상태라 구체적인 에러문은 복귀후 추가 하겠습니다.

**Comment by wlsdml1114** [comment]
wav로 변경하고 해보시겠어요?

**Comment by popop098** [comment]
wav로 잘 저장되는것을 확인했습니다!
