### ISSUE TITLE
데이터 전처리 과정의 오류

### ISSUE THREAD

**Issue by dlfmadksla279** [wlsdml1114/diff-svc#32]
(diff-svc) C:\svc\diff-svc-main>python sep_wav.py
D:\gdzfgvadfSD\envs\diff-svc\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
mp4 to wav 변환 작업 중...:   0%|                                                               | 0/42 [00:00<?, ?it/s]D:\gdzfgvadfSD\envs\diff-svc\lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
mp4 to wav 변환 작업 중...:   7%|███▊                                                  | 3/42 [00:00<00:00, 763.34it/s]
Traceback (most recent call last):
  File "C:\svc\diff-svc-main\sep_wav.py", line 285, in <module>
    main(
  File "C:\svc\diff-svc-main\sep_wav.py", line 158, in main
    mp4_to_wav(input_dir,filename)
  File "C:\svc\diff-svc-main\sep_wav.py", line 89, in mp4_to_wav
    track = AudioSegment.from_file(os.path.join(input_dir,input_file),  format= 'mp4')
  File "D:\gdzfgvadfSD\envs\diff-svc\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "D:\gdzfgvadfSD\envs\diff-svc\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "D:\gdzfgvadfSD\envs\diff-svc\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\gdzfgvadfSD\envs\diff-svc\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다

중간에 c드라이브와 d드라이브가 섞여 나오는 걸 보면 설치가 꼬인듯 싶은데 어디서 꼬였는지 모르겠네요

**Comment by wlsdml1114** [comment]
ffmpeg를 설치하신 뒤에 환경변수 PATH에 등록을 하신건지 확인이 필요한거 같습니다.
`warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)`
라고 에러가 뜨는걸 보니 ffmpeg의 위치를 찾을 수 없는 거 같습니다

**Comment by dlfmadksla279** [comment]
> ffmpeg를 설치하신 뒤에 환경변수 PATH에 등록을 하신건지 확인이 필요한거 같습니다. 라고 에러가 뜨는걸 보니 ffmpeg의 위치를 찾을 수 없는 거 같습니다`warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)`

압축해제 한 뒤에 환경변수 path에 등록은 했는데, 혹시 설치 경로에 한글이 들어가 있으면 인식을 못하나요?

**Comment by wlsdml1114** [comment]
엄.. 모르겠습니다
아마 잘 안될거 같긴한데
테스트 해보시려면 anaconda prompt열고 
`ffmpeg`한번 쳐보세용

**Comment by dlfmadksla279** [comment]
> 엄.. 모르겠습니다 아마 잘 안될거 같긴한데 테스트 해보시려면 anaconda prompt열고 `ffmpeg`한번 쳐보세용

아나콘다에서 입력시 (base) C:\Windows\System32>ffmpeg
'ffmpeg'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.

일반 cmd에서 입력시
ffmpeg version 2023-04-06-git-b564ad8eac-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  6.100 / 58.  6.100
  libavcodec     60.  9.100 / 60.  9.100
  libavformat    60.  4.101 / 60.  4.101
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  5.100 /  9.  5.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

컴퓨터 프로그램은 처음이라 잘 모르겠네요....

**Comment by MoorDev** [comment]
Ffmpeg가 본래 리눅스에서 쓰는걸 상정하고 만든거라 윈도에선 불편합니다 아나콘다도 사실 리눅스가 우선 지원이고요.

일단은 path 설정은 제대로 되어있는듯 하지만 아나콘다가 꼬인것 같습니다. 아나콘다내부에 ffmpeg 설치를해봐야 할듯 합니다.
conda install -c conda-forge ffmpeg
윈도용 아나콘다는 사실 리눅스 환경을 흉내내고 있거든요.

**Comment by dlfmadksla279** [comment]
> Ffmpeg가 본래 리눅스에서 쓰는걸 상정하고 만든거라 윈도에선 불편합니다 아나콘다도 사실 리눅스가 우선 지원이고요.
> 
> 일단은 path 설정은 제대로 되어있는듯 하지만 아나콘다가 꼬인것 같습니다. 아나콘다내부에 ffmpeg 설치를해봐야 할듯 합니다. conda install -c conda-forge ffmpeg 윈도용 아나콘다는 사실 리눅스 환경을 흉내내고 있거든요.

파일 경로 중간에 한글이 들어가서 이랬었네요.
아예 C드라이브에 폴더를 놓으니 해결됐습니다. 

도와주셔서 감사합니다.
