### ISSUE TITLE
고음을 지르는 데이터가 없을 때

### ISSUE THREAD

**Issue by seohyunp69** [wlsdml1114/diff-svc#33]
일반 말하는 데이터에 피치를 올려서 (음성변조하듯이)데이터에 추가하면 어느정도 커버가 될까여..?

**Comment by wlsdml1114** [comment]
아마 퀄리티가 엄청 안좋을것으로 예상됩니다..
일반 말하는데이터로 학습한 결과물에 pitch를 적용하는게 더 나을수도 있을 것 같습니다.
