### ISSUE TITLE
기타 ) 이 레포를 위한 디스코드 서포트 서버

### ISSUE THREAD

**Issue by popop098** [wlsdml1114/diff-svc#35]
제목 그대로 깃헙 이슈를 통한 질의응답보다 디스코드 서버를 생성하여 해당 서버에서 실시간으로 질의응답을 하는게 어떨까합니다.

**Comment by wlsdml1114** [comment]
github issue를 사용하는 이유는 질문답변 히스토리를 체계적으로 남겨서 초보자분들이 같은 질문을 여러번 하는것을 방지하기 위함이 가장 큽니다.
코딩을 하실 줄 아는분들이면 제가 그랬던거 처럼 원래 레포지토리의 디스코드 서버에서 이미 얘기를 자유롭게 나누실거 같기도 하구요.
그쪽에 더 능력자분들이 많으시고 경험도 많아셔서 굳이 별개로 만들필요는 없을 것 같습니다.
다만 만드신다고 하면 본 레포지토리에 링크를 등록시켜드리겠습니다.

**Comment by popop098** [comment]
아무래도 영어로 대화해야해서 초보이신 분들이 대화하기에 어려움을 겪으실것같아 생성해서 도움을 주고받는게 좋을듯하여 추후 준비가 완료되는대로 링크남기겠습니다.

**Comment by wlsdml1114** [comment]
네 여기 이슈에 달아주시면 확인하는대로 추가하겠습니다.

**Comment by popop098** [comment]
생성했습니다. 아래링크를 통해 접속하실수있습니다.
만일 wlsdml1114님이 접속하신다면 `gawi#9537`로 연락바랍니다.(staff역할 및 Owner역할 지급을 위함)
https://nguard.xyz/invite/diffsvckr

**Comment by wlsdml1114** [comment]
cb1c600e6a5f2749f0c55bd29d8339125100b3fc
감사합니다. 
리드미에 추가했습니다.
