### ISSUE TITLE
혹시 노래 key 설정은 어떻게 하나요?

### ISSUE THREAD

**Issue by wnsvy1113** [wlsdml1114/diff-svc#37]
무반주파일의 음역대가 너무 낮거나 높을때 결과물 뽑을때 음역대를 조절하는 방법이 따로 있나요?
자꾸 결과물을 뽑으면 고음을 너무 힘들어해서요..

**Comment by popop098** [comment]
https://github.com/wlsdml1114/diff-svc/blob/331085b06664a81273a4e3019b8f59e8100b2617/infer.py#L82
위 코드에서 설정하실수있습니다.

**Comment by MoorDev** [comment]
해당 키값 최대는 12입니다. 이 이상은 무조건 깨진 소리가 납니다. (문서에 쓰여있습니다)
제가 만든 녀석은 저음을 힘들어해서 실제 사람이 녹음했을 때처럼 피치를 만져서 뽑았습니다...무슨 가래낀 소리가 나서 저음 데이터를 더 넣어야하나 싶네요.

**Comment by wnsvy1113** [comment]
감사합니다! 👍
