### ISSUE TITLE
학습한 것 보관해서 꺼내쓰기

### ISSUE THREAD

**Issue by seohyunp69** [wlsdml1114/diff-svc#39]
checkpoints 폴더에 있는 ckpt파일 복사해서 갖고 다니면 되나여? 아니라면 어캐해야하나여

**Comment by MoorDev** [comment]
Checkpoints폴더전체와 저장소 전체의코드 그리고 파이썬 환경(env)까지 함께하는걸 추천 합니다. 학습환경까지 백업해야 정상적인 세팅이 남습니다.

전 전체를 백업한다고 하면 OS전체를 이미지화 해버립니다. OS환경에 따른 영향도 생각보다 크더군요. 제가 윈도우가 아닌 리눅스를 사용하는 이유기도 합니다.
