### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by teril43** [wlsdml1114/diff-svc#4]
바이너라이즈 실행 시

(base) D:\AIKoe\config\diff-svc-main>conda activate diff-svc

(diff-svc) D:\AIKoe\config\diff-svc-main>set PYTHONPATH=.

(diff-svc) D:\AIKoe\config\diff-svc-main>set CUDA_VISIBLE_DEVICES=0

(diff-svc) D:\AIKoe\config\diff-svc-main>python preprocessing/binarize.py --config training/config.yaml
| Hparams chains:  ['training/config.yaml']
| Hparams:
K_step: 1000, accumulate_grad_batches: 1, audio_num_mel_bins: 80, audio_sample_rate: 24000, binarization_args: {'shuffle': False, 'with_align': True, 'with_f0': True, 'with_hubert': True, 'with_spk_embed': False, 'with_wav': False},
binarizer_cls: preprocessing.SVCpre.SVCBinarizer, binary_data_dir: data/binary/test2, check_val_every_n_epoch: 10, choose_test_manually: False, clip_grad_norm: 1,
config_path: training/config.yaml, content_cond_steps: [], cwt_add_f0_loss: False, cwt_hidden_size: 128, cwt_layers: 2,
cwt_loss: l1, cwt_std_scale: 0.8, datasets: ['opencpop'], debug: False, dec_ffn_kernel_size: 9,
dec_layers: 4, decay_steps: 40000, decoder_type: fft, dict_dir: , diff_decoder_type: wavenet,
diff_loss_type: l2, dilation_cycle_length: 4, dropout: 0.1, ds_workers: 4, dur_enc_hidden_stride_kernel: ['0,2,3', '0,2,3', '0,1,3'],
dur_loss: mse, dur_predictor_kernel: 3, dur_predictor_layers: 5, enc_ffn_kernel_size: 9, enc_layers: 4,
encoder_K: 8, encoder_type: fft, endless_ds: False, f0_bin: 256, f0_max: 1100.0,
f0_min: 50.0, ffn_act: gelu, ffn_padding: SAME, fft_size: 512, fmax: 12000,
fmin: 30, fs2_ckpt: , gaussian_start: True, gen_dir_name: , gen_tgt_spk_id: -1,
hidden_size: 256, hop_size: 128, hubert_gpu: True, hubert_path: checkpoints/hubert/hubert_soft.pt, infer: False,
keep_bins: 80, lambda_commit: 0.25, lambda_energy: 0.0, lambda_f0: 1.0, lambda_ph_dur: 0.3,
lambda_sent_dur: 1.0, lambda_uv: 1.0, lambda_word_dur: 1.0, load_ckpt: , log_interval: 100,
loud_norm: False, lr: 0.0004, max_beta: 0.02, max_epochs: 3000, max_eval_sentences: 1,
max_eval_tokens: 60000, max_frames: 42000, max_input_tokens: 60000, max_sentences: 35, max_tokens: 128000,
max_updates: 1000000, mel_loss: ssim:0.5|l1:0.5, mel_vmax: 1.5, mel_vmin: -6.0, min_level_db: -120,
no_fs2: True, norm_type: gn, num_ckpt_keep: 10, num_heads: 2, num_sanity_val_steps: 1,
num_spk: 1, num_test_samples: 0, num_valid_plots: 10, optimizer_adam_beta1: 0.9, optimizer_adam_beta2: 0.98,
out_wav_norm: False, pe_ckpt: checkpoints/0102_xiaoma_pe/model_ckpt_steps_60000.ckpt, pe_enable: False, perform_enhance: True, pitch_ar: False,
pitch_enc_hidden_stride_kernel: ['0,2,5', '0,2,5', '0,2,5'], pitch_extractor: parselmouth, pitch_loss: l2, pitch_norm: log, pitch_type: frame,
pndm_speedup: 10, pre_align_args: {'allow_no_txt': False, 'denoise': False, 'forced_align': 'mfa', 'txt_processor': 'zh_g2pM', 'use_sox': True, 'use_tone': False}, pre_align_cls: data_gen.singing.pre_align.SingingPreAlign, predictor_dropout: 0.5, predictor_grad: 0.1,
predictor_hidden: -1, predictor_kernel: 5, predictor_layers: 5, prenet_dropout: 0.5, prenet_hidden_size: 256,
pretrain_fs_ckpt: , processed_data_dir: xxx, profile_infer: False, raw_data_dir: data/raw/test2, ref_norm_layer: bn,
rel_pos: True, reset_phone_dict: True, residual_channels: 256, residual_layers: 20, save_best: False,
save_ckpt: True, save_codes: ['configs', 'modules', 'src', 'utils'], save_f0: True, save_gt: False, schedule_type: linear,
seed: 1234, sort_by_len: True, speaker_id: test2, spec_max: [-1.5451143980026245, -1.5177826881408691, -1.1807013750076294, -0.6732071042060852, -0.47006210684776306, -0.271837055683136, -0.27174147963523865, -0.3395537734031677, -0.2529868483543396, -0.22453370690345764, -0.24767500162124634, -0.22861438989639282, -0.28668588399887085, -0.335957795381546, -0.3118636906147003, -0.34530898928642273, -0.35274678468704224, -0.4730182886123657, -0.45395755767822266, -0.4338522255420685, -0.41395917534828186, -0.29468369483947754, -0.16852207481861115, -0.3900046646595001, -0.6241626739501953, -0.5899035930633545, -0.6534764170646667, -0.6667397022247314, -0.6992383003234863, -0.7867978811264038, -0.8457596302032471, -0.43350857496261597, -0.629216730594635, -0.9135912656784058, -0.9230040311813354, -0.6756577491760254, -0.8399246335029602, -0.8495144248008728, -0.781493067741394, -1.0347247123718262, -1.0051935911178589, -1.1246198415756226, -1.021154522895813, -0.851677417755127, -0.8443652987480164, -0.9016147255897522, -0.7618780732154846, -1.0490750074386597, -1.2046996355056763, -1.2022035121917725, -0.9753153324127197, -1.2503044605255127, -1.0664823055267334, -1.1236635446548462, -1.2223032712936401, -1.0116488933563232, -1.2263423204421997, -1.2552075386047363, -1.3846945762634277, -1.2681812047958374, -1.3416036367416382, -1.264938235282898, -1.2763726711273193, -1.4651004076004028, -1.4880361557006836, -1.5735552310943604, -1.4097294807434082, -1.468385100364685, -1.3768259286880493, -1.3312186002731323, -1.3547866344451904, -1.4387739896774292, -1.1861546039581299, -1.1709729433059692, -1.1812609434127808, -1.1489264965057373, -1.5605546236038208, -2.2702553272247314, -4.064557075500488, -5.809507846832275], spec_min: [-5.740882873535156, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -5.959110260009766, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -5.999546527862549, -6.0, -5.995517730712891, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -5.960205078125, -5.93423318862915, -6.0, -5.933608531951904, -6.0, -6.0, -6.0, -5.953958511352539, -5.908934593200684, -5.911312580108643, -5.882552623748779, -5.932425498962402, -5.91495943069458, -5.826524257659912, -5.777952671051025, -5.775007724761963, -5.849961280822754, -5.7793660163879395, -5.781087875366211, -5.818603992462158, -5.765895366668701, -5.834509372711182, -5.817623615264893, -5.855445384979248, -5.844409465789795, -5.760529518127441, -5.713063716888428, -5.74588680267334, -5.855954647064209, -5.874588489532471, -5.81571626663208, -5.849369049072266, -5.963766574859619, -5.8541646003723145, -5.922942161560059, -6.0, -6.0, -6.0, -6.0],
spk_cond_steps: [], stop_token_weight: 5.0, task_cls: training.task.SVC_task.SVCTask, test_ids: [], test_input_dir: ,
test_num: 0, test_prefixes: ['test'], test_set_name: test, timesteps: 1000, train_set_name: train,
use_crepe: True, use_denoise: False, use_energy_embed: False, use_gt_dur: False, use_gt_f0: False,
use_midi: False, use_nsf: True, use_pitch_embed: True, use_pos_embed: True, use_spk_embed: False,
use_spk_id: False, use_split_spk_id: False, use_uv: False, use_var_enc: False, use_vec: False,
val_check_interval: 2000, valid_num: 0, valid_set_name: valid, validate: False, vocoder: network.vocoders.hifigan.HifiGAN,
vocoder_ckpt: checkpoints/0109_hifigan_bigpopcs_hop128, warmup_updates: 2000, wav2spec_eps: 1e-6, weight_decay: 0, win_size: 512,
work_dir: ,
| Binarizer:  <class 'preprocessing.SVCpre.SVCBinarizer'>
spkers:  {'test2'}
| spk_map:  {'test2': 0}
  0%|                                                                                            | 0/5 [00:00<?, ?it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (9).wav, wav_fn: data\raw\test2\01 (9).wav
 20%|████████████████▊                                                                   | 1/5 [00:00<00:02,  1.91it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (8).wav, wav_fn: data\raw\test2\01 (8).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (7).wav, wav_fn: data\raw\test2\01 (7).wav
 60%|██████████████████████████████████████████████████▍                                 | 3/5 [00:00<00:00,  5.12it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (6).wav, wav_fn: data\raw\test2\01 (6).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (5).wav, wav_fn: data\raw\test2\01 (5).wav
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  5.83it/s]
| valid total duration: 0.000s
  0%|                                                                                            | 0/5 [00:00<?, ?it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (9).wav, wav_fn: data\raw\test2\01 (9).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (8).wav, wav_fn: data\raw\test2\01 (8).wav
 40%|█████████████████████████████████▌                                                  | 2/5 [00:00<00:00, 16.95it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (7).wav, wav_fn: data\raw\test2\01 (7).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (6).wav, wav_fn: data\raw\test2\01 (6).wav
 80%|███████████████████████████████████████████████████████████████████▏                | 4/5 [00:00<00:00, 11.94it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (5).wav, wav_fn: data\raw\test2\01 (5).wav
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 12.72it/s]
| test total duration: 0.000s
  0%|                                                                                           | 0/30 [00:00<?, ?it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (4).wav, wav_fn: data\raw\test2\01 (4).wav
  3%|██▊                                                                                | 1/30 [00:00<00:04,  6.29it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (35).wav, wav_fn: data\raw\test2\01 (35).wav
  7%|█████▌                                                                             | 2/30 [00:00<00:04,  6.79it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (34).wav, wav_fn: data\raw\test2\01 (34).wav
 10%|████████▎                                                                          | 3/30 [00:00<00:03,  7.39it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (33).wav, wav_fn: data\raw\test2\01 (33).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (32).wav, wav_fn: data\raw\test2\01 (32).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (31).wav, wav_fn: data\raw\test2\01 (31).wav
 20%|████████████████▌                                                                  | 6/30 [00:00<00:01, 14.15it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (30).wav, wav_fn: data\raw\test2\01 (30).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (3).wav, wav_fn: data\raw\test2\01 (3).wav
 27%|██████████████████████▏                                                            | 8/30 [00:00<00:01, 15.16it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (29).wav, wav_fn: data\raw\test2\01 (29).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (28).wav, wav_fn: data\raw\test2\01 (28).wav
 33%|███████████████████████████▎                                                      | 10/30 [00:00<00:01, 13.58it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (27).wav, wav_fn: data\raw\test2\01 (27).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (26).wav, wav_fn: data\raw\test2\01 (26).wav
 40%|████████████████████████████████▊                                                 | 12/30 [00:00<00:01, 12.91it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (25).wav, wav_fn: data\raw\test2\01 (25).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (24).wav, wav_fn: data\raw\test2\01 (24).wav
 47%|██████████████████████████████████████▎                                           | 14/30 [00:01<00:01, 13.04it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (23).wav, wav_fn: data\raw\test2\01 (23).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (22).wav, wav_fn: data\raw\test2\01 (22).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (21).wav, wav_fn: data\raw\test2\01 (21).wav
 57%|██████████████████████████████████████████████▍                                   | 17/30 [00:01<00:00, 15.94it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (20).wav, wav_fn: data\raw\test2\01 (20).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (2).wav, wav_fn: data\raw\test2\01 (2).wav
 63%|███████████████████████████████████████████████████▉                              | 19/30 [00:01<00:00, 16.44it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (19).wav, wav_fn: data\raw\test2\01 (19).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (18).wav, wav_fn: data\raw\test2\01 (18).wav
 70%|█████████████████████████████████████████████████████████▍                        | 21/30 [00:01<00:00, 16.90it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (17).wav, wav_fn: data\raw\test2\01 (17).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (16).wav, wav_fn: data\raw\test2\01 (16).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (15).wav, wav_fn: data\raw\test2\01 (15).wav
 80%|█████████████████████████████████████████████████████████████████▌                | 24/30 [00:01<00:00, 20.11it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (14).wav, wav_fn: data\raw\test2\01 (14).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (13).wav, wav_fn: data\raw\test2\01 (13).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (12).wav, wav_fn: data\raw\test2\01 (12).wav
 90%|█████████████████████████████████████████████████████████████████████████▊        | 27/30 [00:01<00:00, 16.15it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (11).wav, wav_fn: data\raw\test2\01 (11).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (10).wav, wav_fn: data\raw\test2\01 (10).wav
| Skip item (Torch not compiled with CUDA enabled). item_name: data\raw\test2\01 (1).wav, wav_fn: data\raw\test2\01 (1).wav
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:01<00:00, 15.22it/s]
Traceback (most recent call last):
  File "D:\AIKoe\config\diff-svc-main\preprocessing\binarize.py", line 20, in <module>
    binarize()
  File "D:\AIKoe\config\diff-svc-main\preprocessing\binarize.py", line 15, in binarize
    binarizer_cls().process()
  File "D:\AIKoe\config\diff-svc-main\preprocessing\base_binarizer.py", line 137, in process
    self.process_data_split('train')
  File "D:\AIKoe\config\diff-svc-main\preprocessing\base_binarizer.py", line 175, in process_data_split
    spec_max=np.max(spec_max,0)
  File "<__array_function__ internals>", line 180, in amax
  File "C:\Users\Administrator\anaconda3\envs\diff-svc\lib\site-packages\numpy\core\fromnumeric.py", line 2793, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "C:\Users\Administrator\anaconda3\envs\diff-svc\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

(diff-svc) D:\AIKoe\config\diff-svc-main>

바이너라이즈는 안 됐으나 학습 실행해 봤을 시

(diff-svc) D:\AIKoe\config\diff-svc-main>python run.py --config training/config.yaml --exp_name test2 --reset
| Hparams chains:  ['training/config.yaml']
| Hparams:
K_step: 1000, accumulate_grad_batches: 1, audio_num_mel_bins: 80, audio_sample_rate: 24000, binarization_args: {'shuffle': False, 'with_align': True, 'with_f0': True, 'with_hubert': True, 'with_spk_embed': False, 'with_wav': False},
binarizer_cls: preprocessing.SVCpre.SVCBinarizer, binary_data_dir: data/binary/test2, check_val_every_n_epoch: 10, choose_test_manually: False, clip_grad_norm: 1,
config_path: training/config.yaml, content_cond_steps: [], cwt_add_f0_loss: False, cwt_hidden_size: 128, cwt_layers: 2,
cwt_loss: l1, cwt_std_scale: 0.8, datasets: ['opencpop'], debug: False, dec_ffn_kernel_size: 9,
dec_layers: 4, decay_steps: 40000, decoder_type: fft, dict_dir: , diff_decoder_type: wavenet,
diff_loss_type: l2, dilation_cycle_length: 4, dropout: 0.1, ds_workers: 4, dur_enc_hidden_stride_kernel: ['0,2,3', '0,2,3', '0,1,3'],
dur_loss: mse, dur_predictor_kernel: 3, dur_predictor_layers: 5, enc_ffn_kernel_size: 9, enc_layers: 4,
encoder_K: 8, encoder_type: fft, endless_ds: False, f0_bin: 256, f0_max: 1100.0,
f0_min: 50.0, ffn_act: gelu, ffn_padding: SAME, fft_size: 512, fmax: 12000,
fmin: 30, fs2_ckpt: , gaussian_start: True, gen_dir_name: , gen_tgt_spk_id: -1,
hidden_size: 256, hop_size: 128, hubert_gpu: True, hubert_path: checkpoints/hubert/hubert_soft.pt, infer: False,
keep_bins: 80, lambda_commit: 0.25, lambda_energy: 0.0, lambda_f0: 1.0, lambda_ph_dur: 0.3,
lambda_sent_dur: 1.0, lambda_uv: 1.0, lambda_word_dur: 1.0, load_ckpt: , log_interval: 100,
loud_norm: False, lr: 0.0004, max_beta: 0.02, max_epochs: 3000, max_eval_sentences: 1,
max_eval_tokens: 60000, max_frames: 42000, max_input_tokens: 60000, max_sentences: 35, max_tokens: 128000,
max_updates: 1000000, mel_loss: ssim:0.5|l1:0.5, mel_vmax: 1.5, mel_vmin: -6.0, min_level_db: -120,
no_fs2: True, norm_type: gn, num_ckpt_keep: 10, num_heads: 2, num_sanity_val_steps: 1,
num_spk: 1, num_test_samples: 0, num_valid_plots: 10, optimizer_adam_beta1: 0.9, optimizer_adam_beta2: 0.98,
out_wav_norm: False, pe_ckpt: checkpoints/0102_xiaoma_pe/model_ckpt_steps_60000.ckpt, pe_enable: False, perform_enhance: True, pitch_ar: False,
pitch_enc_hidden_stride_kernel: ['0,2,5', '0,2,5', '0,2,5'], pitch_extractor: parselmouth, pitch_loss: l2, pitch_norm: log, pitch_type: frame,
pndm_speedup: 10, pre_align_args: {'allow_no_txt': False, 'denoise': False, 'forced_align': 'mfa', 'txt_processor': 'zh_g2pM', 'use_sox': True, 'use_tone': False}, pre_align_cls: data_gen.singing.pre_align.SingingPreAlign, predictor_dropout: 0.5, predictor_grad: 0.1,
predictor_hidden: -1, predictor_kernel: 5, predictor_layers: 5, prenet_dropout: 0.5, prenet_hidden_size: 256,
pretrain_fs_ckpt: , processed_data_dir: xxx, profile_infer: False, raw_data_dir: data/raw/test2, ref_norm_layer: bn,
rel_pos: True, reset_phone_dict: True, residual_channels: 256, residual_layers: 20, save_best: False,
save_ckpt: True, save_codes: ['configs', 'modules', 'src', 'utils'], save_f0: True, save_gt: False, schedule_type: linear,
seed: 1234, sort_by_len: True, speaker_id: test2, spec_max: [-1.5451143980026245, -1.5177826881408691, -1.1807013750076294, -0.6732071042060852, -0.47006210684776306, -0.271837055683136, -0.27174147963523865, -0.3395537734031677, -0.2529868483543396, -0.22453370690345764, -0.24767500162124634, -0.22861438989639282, -0.28668588399887085, -0.335957795381546, -0.3118636906147003, -0.34530898928642273, -0.35274678468704224, -0.4730182886123657, -0.45395755767822266, -0.4338522255420685, -0.41395917534828186, -0.29468369483947754, -0.16852207481861115, -0.3900046646595001, -0.6241626739501953, -0.5899035930633545, -0.6534764170646667, -0.6667397022247314, -0.6992383003234863, -0.7867978811264038, -0.8457596302032471, -0.43350857496261597, -0.629216730594635, -0.9135912656784058, -0.9230040311813354, -0.6756577491760254, -0.8399246335029602, -0.8495144248008728, -0.781493067741394, -1.0347247123718262, -1.0051935911178589, -1.1246198415756226, -1.021154522895813, -0.851677417755127, -0.8443652987480164, -0.9016147255897522, -0.7618780732154846, -1.0490750074386597, -1.2046996355056763, -1.2022035121917725, -0.9753153324127197, -1.2503044605255127, -1.0664823055267334, -1.1236635446548462, -1.2223032712936401, -1.0116488933563232, -1.2263423204421997, -1.2552075386047363, -1.3846945762634277, -1.2681812047958374, -1.3416036367416382, -1.264938235282898, -1.2763726711273193, -1.4651004076004028, -1.4880361557006836, -1.5735552310943604, -1.4097294807434082, -1.468385100364685, -1.3768259286880493, -1.3312186002731323, -1.3547866344451904, -1.4387739896774292, -1.1861546039581299, -1.1709729433059692, -1.1812609434127808, -1.1489264965057373, -1.5605546236038208, -2.2702553272247314, -4.064557075500488, -5.809507846832275], spec_min: [-5.740882873535156, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -5.959110260009766, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -5.999546527862549, -6.0, -5.995517730712891, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -5.960205078125, -5.93423318862915, -6.0, -5.933608531951904, -6.0, -6.0, -6.0, -5.953958511352539, -5.908934593200684, -5.911312580108643, -5.882552623748779, -5.932425498962402, -5.91495943069458, -5.826524257659912, -5.777952671051025, -5.775007724761963, -5.849961280822754, -5.7793660163879395, -5.781087875366211, -5.818603992462158, -5.765895366668701, -5.834509372711182, -5.817623615264893, -5.855445384979248, -5.844409465789795, -5.760529518127441, -5.713063716888428, -5.74588680267334, -5.855954647064209, -5.874588489532471, -5.81571626663208, -5.849369049072266, -5.963766574859619, -5.8541646003723145, -5.922942161560059, -6.0, -6.0, -6.0, -6.0],
spk_cond_steps: [], stop_token_weight: 5.0, task_cls: training.task.SVC_task.SVCTask, test_ids: [], test_input_dir: ,
test_num: 0, test_prefixes: ['test'], test_set_name: test, timesteps: 1000, train_set_name: train,
use_crepe: True, use_denoise: False, use_energy_embed: False, use_gt_dur: False, use_gt_f0: False,
use_midi: False, use_nsf: True, use_pitch_embed: True, use_pos_embed: True, use_spk_embed: False,
use_spk_id: False, use_split_spk_id: False, use_uv: False, use_var_enc: False, use_vec: False,
val_check_interval: 2000, valid_num: 0, valid_set_name: valid, validate: False, vocoder: network.vocoders.hifigan.HifiGAN,
vocoder_ckpt: checkpoints/0109_hifigan_bigpopcs_hop128, warmup_updates: 2000, wav2spec_eps: 1e-6, weight_decay: 0, win_size: 512,
work_dir: checkpoints/test2,
| Mel losses: {'ssim': 0.5, 'l1': 0.5}
| load HifiGAN:  checkpoints/0109_hifigan_bigpopcs_hop128\model_ckpt_steps_1512000.ckpt
Removing weight norm...
| Loaded model parameters from checkpoints/0109_hifigan_bigpopcs_hop128\model_ckpt_steps_1512000.ckpt.
| HifiGAN device: cpu.
03/19 02:22:07 AM gpu available: False, used: True
| model Trainable Parameters: 16.827M
Traceback (most recent call last):
  File "D:\AIKoe\config\diff-svc-main\run.py", line 15, in <module>
    run_task()
  File "D:\AIKoe\config\diff-svc-main\run.py", line 11, in run_task
    task_cls.start()
  File "D:\AIKoe\config\diff-svc-main\training\task\base_task.py", line 234, in start
    trainer.fit(task)
  File "D:\AIKoe\config\diff-svc-main\utils\pl_utils.py", line 494, in fit
    model.cuda(self.root_gpu)
  File "C:\Users\Administrator\anaconda3\envs\diff-svc\lib\site-packages\torch\nn\modules\module.py", line 749, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Administrator\anaconda3\envs\diff-svc\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\Administrator\anaconda3\envs\diff-svc\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\Administrator\anaconda3\envs\diff-svc\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\Administrator\anaconda3\envs\diff-svc\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "C:\Users\Administrator\anaconda3\envs\diff-svc\lib\site-packages\torch\nn\modules\module.py", line 749, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Administrator\anaconda3\envs\diff-svc\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

(diff-svc) D:\AIKoe\config\diff-svc-main>

영상에 따라 아나콘다 3 등을 설치, 패스 연결 후

conda create -n diff-svc python=3.9
conda activate diff-svc
conda install pytorch==1.13.1 torchvision torchaudio -c pytorch -c nvidia
pip install -r requirements.txt < 토치라이트닝 pytorch_lightning==1.7.7 으로 변경해서
설치를 진행해봤습니다.
계속 동일한 문제가 발생합니다.

**Comment by teril43** [comment]
아래에 같은 문제를 겪고 해결하신 분이 계시네요. 
pip uninstall torch
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu116 로
바이너라이즈는 해결됐습니다. 
바이너라이즈 후 학습 진행해보도록 하겠습니다.
신경써주셔서 감사합니다.

**Comment by teril43** [comment]
학습도 문제없이 진행됩니다.

**Comment by wlsdml1114** [comment]
감사합니다
해당내용 README에 적용해두었습니다.
