### ISSUE TITLE
config.yaml파일 질문

### ISSUE THREAD

**Issue by seohyunp69** [wlsdml1114/diff-svc#40]
K_step: 1000
accumulate_grad_batches: 1
audio_num_mel_bins: 80
audio_sample_rate: 24000

debug: false
dec_ffn_kernel_size: 9
dec_layers: 4
decay_steps: 40000
decoder_type: fft
dict_dir: ''
diff_decoder_type: wavenet
diff_loss_type: l2
dilation_cycle_length: 4
dropout: 0.1

저번에 설정 다 체크해봐도 학습속도가 심각하게 느리다고 한 사람입니다.
혹시 여기서 설정을 건드리면 뭔가 있지 않을까 해서 이것들이 각각 뭘 뜻하는 건지 질문합니다..

**Comment by MoorDev** [comment]
일단 여기서 조정해야 할게 decay steps입니다.
 Learning Rate를 어느정도 학습 후에 줄일것인가를 설정하는 값 입니다. 
Max sentence를 줄였다면 이쪽을 반대로 늘려주셔야 합니다. 

학습속도와 이쪽은 크게 관계가 없습니다
