### ISSUE TITLE
total loss와 lr 크기가 잘 안 줄어듭니다.

### ISSUE THREAD

**Issue by deaganazi** [wlsdml1114/diff-svc#41]
현재 236000스텝까지 하였는데 다른 사람들 이야기 들어보면 10만 넘으면 대부분 total loss가 많이 줄어드는 거 같던데 저는 한번 돌릴 때 가끔 엄청 낮아지는 경우(0.0009까지 봤습니다)를 빼곤 계속 왔다 갔다 합니다. lr 크기도 5-e5였다가 20만 스텝 들어서면서 2.5-e5가 됬네요. 학습할 데이터의 양이 많다기엔 1시간 30분? 2시간 정도의 분량이고 그래픽카드도 3060 12gb입니다. 혹시 끊었다 돌렸다 하는 게 문제였을까요? total loss가 안정화될 때까지 돌려봐야 할까요?
+)추가
그래픽 카드 용량이 6gb 넘으면 config_nsf.yaml로 돌리라고 하셨는데 
 raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SVCTask:
이런 에러와 함께 size missmatch라고 뜨면서 엄청 길게 오류가 나며 자꾸 안되네요

**Comment by popop098** [comment]
음원데이터가 44.1kHz, 모노인지 확인하시고 또는 hifigan전용 checkpoint를 설치하셨는지 확인바랍니다.
![image](https://user-images.githubusercontent.com/53284350/230749615-286f70b7-7595-4e25-b551-8dc045642620.png)

**Comment by MoorDev** [comment]
lr은 사실 옵션으로 조정합니다. 데이터가 많아서 그렇다기보다 학습하기 어려워서 그런 경우도 있습니다. 일단 max sentence를 늘려주세요. 그리고 decay steps를 그만큼 줄이시면 됩니다.
12GB짜리니까 어느정도 늘려도 넉넉할겁니다. 6GB넘는다고 config_nsf로 꼭 돌릴필요는 없습니다. 22.5kHz보다 44.1kHz결과가 당연히 더 좋기에 그런겁니다.
몇몇 이유로 44.1kHz는 pe를 쓸 수 없는 문제가 있습니다. 그래서 일부 음성에서 결과가 좋지 않아 둘을 섞어서 쓰는 사람도 있습니다.

Decay를 줄여주시면 lr이 그만큼 빠르게 줄어듭니다. 다만 결과물이 이상한 곳으로 발산해버릴 가능성이 높아집니다. 이것도 감안해서 쓰셔야 합니다. 

그리고 전 lr 5e-5에서 괜찮은 결과물이 뽑혔습니다. 데이터 품질이 좋으면 total loss와 관계없이 그만큼 결과물이 무조건 좋습니다.
