### ISSUE TITLE
설치 위치 바꾸기

### ISSUE THREAD

**Issue by seohyunp69** [wlsdml1114/diff-svc#42]
diff svc main을 다른 폴더로 옮기고 싶은데 그냥 옮기면 되는건가요??
(+원래 애초부터 다른 디스크에 깔려고 했는데 anaconda cmd?에서 아무리 cd (위치) 쳐도 c드라이브 외에 다른 것은 안되더라고요.. 디스크 이름에 한글이 들어가서 그런 건가요?)

**Comment by MoorDev** [comment]
윈도cmd에서 다른 드라이브로 가려면
D: (엔터)
이런식으로 쳐서 넘어가면 됩니다. 도스때부터 내려온 고유의 방식입니다. 그 다음 cd명령쓰시면 됩니다

그리고 저장소폴더를 옮기는건 아무래도 상관없습니다
