### ISSUE TITLE
CPU관련 질문이 있습니다

### ISSUE THREAD

**Issue by jiseong1209** [wlsdml1114/diff-svc#43]
제가 학습시킨 목소리 모델을 infer.py를 통해 합성 할 때 GPU가 아예없이 CPU만으로도 동작은 가능한가요?
만약 동작이 된다면 CPU만으로 수행할때 시간이 어느정도 걸릴까요???

**Comment by popop098** [comment]
최소 2배이상은 더 걸릴겁니다.. 괜히 GPU쓰는게 아닌....

**Comment by MoorDev** [comment]
가능합니다.
저는 이 프로젝트를 최적화해서 라즈베리파이에서 돌리는 방법을 찾고 있고 그러기위해선 모든 모델을 cpu에서 돌리는것이 전제되어야 합니다.
현재 메모리 문제가 있고 라즈베리파이3(2GB모델)으로는 파이가 뻗어버리는 문제가 있네요.
CPU로 충분히 가능하고 메모리만 적당하면 느리긴해도 결과를 뽑을 수 있을 겁니다.
