### ISSUE TITLE
total loss가 nan으로 떠요

### ISSUE THREAD

**Issue by dhtjdals1023** [wlsdml1114/diff-svc#45]
valid results: {'total_loss': 1.0017, 'mel': 1.0017}

Epoch 1: : 25batch [01:06,  2.34s/batch, batch_size=10, lr=0.0004, mel=nan, step=24]

 Epoch 0 ended. Steps: 24. {'total_loss': nan, 'mel': 0, 'batch_size': 9.88, 'lr': 0.0004}

재설치해도 계속 같은 증상이에요
컴맹이라 뭐가 문젠지 전혀 모르겠네요 ㅠㅠ

**Comment by MoorDev** [comment]
학습이 너무 느립니다.
CUDA설정이 되어있는지 확인해주시고 학습중 nvidia-smi를 열어서 GPU Util이 올라가는지 메모리 사용율이 얼마나 되는지 확인해주세요.

만약 CUDA에 문제가 있다면 그냥 CPU학습이 더 빠를듯 합니다.
