### ISSUE TITLE
결과물 관련해서 원곡 배경음이랑 합치는법?

### ISSUE THREAD

**Issue by LEELEE412** [wlsdml1114/diff-svc#47]
결과물 확인할때 배경음이랑 목소리 분리해서 학습을 시키는데 다시 배경음을 덧씌우는 방법이 있나요?

**Comment by popop098** [comment]
외부 프로그램을 사용해야합니다 예를 들어 audacity가 있습니다

**Comment by MoorDev** [comment]
무료툴중에서는 Audacity가 가장 편합니다. 
프로그램을 실행하고 변환된 목소리와 배경음을 해당 프로그램에 드래그하면 두개의 트랙이 동시에 열립니다. 그 다음 file-export 하면 됩니다.
