### ISSUE TITLE
학습을 그만뒀다가 이어서 다시 하는 방법

### ISSUE THREAD

**Issue by MoorDev** [wlsdml1114/diff-svc#5]
config.yaml 파일을 열고
load_ckpt: ''
여기에다가 마지막 모델이름 
(예 : 'checkpoints/test/model_ckpt_steps_80000.ckpt')
이렇게 적고 

python run.py --config training/config.yaml --exp_name test
(쉽게 말해서 뒤에 --reset이 빠집니다.)

이렇게 명령을 내리면 이어서 학습이 가능합니다. 이걸 응용하면 잘 학습이 된 모델에 파인 튜닝하는 것도 가능할 겁니다. 저 같은 경우에는 GTX 1650으로 학습해서 너무 오래 걸리는 단점이 있었기에 간간히 중단한 다음 infer로 학습 결과물을 확인 하고 다시 재학습하는 방식을 사용했습니다.

그리고 메모리가 모자라신 분들은 infer.py에서 
hubert_gpu = False
이렇게 해주시고 use_crepe= 부분을 전부 찾아 use_crepe=False 이렇게 고쳐주세요.
infer_tools/infer_toiols.py에도 똑같은 구문이 있습니다. 역시 use_crepe=False 이렇게 고쳐주세요.

학습할 때도 config.yaml 에서 use_crepe 를 False로 고쳐주세요. 이렇게 하면 crepe 대신 parselmouth 라는 알고리즘으로 피치를 분석합니다.
조금 느리지만 메모리는 확실히 확보 가능합니다. 제 피씨로 확인하니 1.5Gb정도 사용합니다. 4GB 그래픽카드로 넉넉하게 학습 가능합니다.

**Comment by wlsdml1114** [comment]
내용 추가 감사합니다.
많은분들이 여쭤보셨던 내용이라 README에 추가해두었습니다.
https://github.com/wlsdml1114/diff-svc/commit/b4ec4b74a5654f6d24292ee38893cb0501fe9a34
