### ISSUE TITLE
ROCm 으론 돌릴방법이없을까요?

### ISSUE THREAD

**Issue by ajajajf2** [wlsdml1114/diff-svc#50]
CPU로만 돌리기엔 너무 오래걸려서 리눅스에서 ROCm으로 돌리고싶은데 방법이 없을까요?

쿠다로만 뜨길래

**Comment by wlsdml1114** [comment]
Pytorch설치할때, ROCm버전으로 설치해보세요
https://pytorch.org/
맞는 세팅찾아서 커맨드따라 설치하시면 될 거같습니다.

**Comment by ajajajf2** [comment]
늘 실행할때 쿠다가없다고떠서요... 그래서 cpu로만돌리는데 많이느리내요 ㅜ

**Comment by wlsdml1114** [comment]
ROCm도 코드 돌릴때는 cuda로 선언하는걸로 알고있는데, 설치가 이상하게 된게 아닐까 싶습니다.

**Comment by MoorDev** [comment]
저도 최근 Rocm은 그냥 CUDA로 해도 잘 된다고 알고 있는데
python3 -c "import torch; print(torch.cuda.is_available())"

Rx580에서 이렇게 했더니 True로 뜨더군요.
혹시 버전은 어떤걸로 하셨나요?
