### ISSUE TITLE
train.py 실행 시 RuntimeError: Given groups=1, weight of size [384, 128, 1], expected input[1, 80, 662] to have 128 channels, but got 80 channels instead

### ISSUE THREAD

**Issue by msforgood** [wlsdml1114/diff-svc#54]
RuntimeError: Given groups=1, weight of size [384, 128, 1], expected input[1, 80, 662] to have 128 channels, but got 80 channels instead
학습이 진행되기 전에 위 에러가 발생합니다.

모델 사이즈를 임의로 변경한 것이 없는데 왜 채널의 개수가 안 맞다고 하는지 모르겠습니다.

**Comment by MoorDev** [comment]
혹시 사전 학습된 모델이 있나요?
사전학습된 모델과 설정이 맞지않아 생기는 문제입니다
