### ISSUE TITLE
지정된 파일을 찾을 수 없습니다 관련입니다

### ISSUE THREAD

**Issue by youchamsae** [wlsdml1114/diff-svc#56]
안녕하세요 선생님, 유튜브에 올려주신 영상으로 차근차근 
제작해보고 있습니다  이렇게 따라할 수 있는 영상을 제작해주셔서 감사드립니다  
영상순서에 맞게 그대로 따라해보고 있는데, 
5분 11초 즈음의 preprocess 폴더에 mp4자료를 넣고 
python sep_wav.py 를 적용하려고 하니 지정된 파일을 찾을 수 없다 하며 진행이 안 됩니다. 
혹시 원인에 대해 도움을 받을 수 있을까요?   제대로 결과물을 내고 싶습니다 ㅜ ㅜ 

(diff-svc) C:\Users\jean0\Downloads\diff-svc-main\diff-svc-main>python sep_wav.py
C:\Users\jean0\anaconda3\envs\diff-svc\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
mp4 to wav 변환 작업 중...:   0%|                                                                | 0/9 [00:00<?, ?it/s]C:\Users\jean0\anaconda3\envs\diff-svc\lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
mp4 to wav 변환 작업 중...:  11%|██████▏                                                 | 1/9 [00:00<00:00, 71.48it/s]
Traceback (most recent call last):
  File "C:\Users\jean0\Downloads\diff-svc-main\diff-svc-main\sep_wav.py", line 285, in <module>
    main(
  File "C:\Users\jean0\Downloads\diff-svc-main\diff-svc-main\sep_wav.py", line 158, in main
    mp4_to_wav(input_dir,filename)
  File "C:\Users\jean0\Downloads\diff-svc-main\diff-svc-main\sep_wav.py", line 89, in mp4_to_wav
    track = AudioSegment.from_file(os.path.join(input_dir,input_file),  format= 'mp4')
  File "C:\Users\jean0\anaconda3\envs\diff-svc\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\jean0\anaconda3\envs\diff-svc\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\jean0\anaconda3\envs\diff-svc\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\jean0\anaconda3\envs\diff-svc\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다

**Comment by MoorDev** [comment]
ffmpeg를 설치하지 않으셨군요

**Comment by cswgogo49** [comment]
저도 이 문제입니다 ffmpeg 설치하고 패스에 환경변수만 등록해주면 되는 건가요? 아니면 혹시 따로 경로 지정해줘야하는 부분이 있는 건가요?ffmpeg설치 되어있고 환경변수도 확인했는데 같은 오류가 뜨네요

**Comment by MoorDev** [comment]
ffmpeg path 환경변수를 bin까지 적어주셔야 합니다.
보통 압축푸시고 압축 푼 경로까지만 넣으시더군요...

**Comment by cswgogo49** [comment]
확인결과 bin까지 들어가있었습니다
(diff-svc) D:\diff-svc-main>python sep_wav.py
D:\anaconda3\envs\diff-svc\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
mp4 to wav 변환 작업 중...: 100%|████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
노멀라이징 작업 중...:   0%|                                                                     | 0/1 [00:00<?, ?it/s]D:\anaconda3\envs\diff-svc\lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
노멀라이징 작업 중...:   0%|                                                                     | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "D:\diff-svc-main\sep_wav.py", line 285, in <module>
    main(
  File "D:\diff-svc-main\sep_wav.py", line 172, in main
    audio_norm(filepath, out_filepath, use_preprocessing)
  File "D:\diff-svc-main\sep_wav.py", line 105, in audio_norm
    rawsound = AudioSegment.from_file(input_filepath, format=ext)
  File "D:\anaconda3\envs\diff-svc\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "D:\anaconda3\envs\diff-svc\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "D:\anaconda3\envs\diff-svc\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\anaconda3\envs\diff-svc\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
위와 같은 오류가 계속 발생합니다 
뭐가 문제인지 봐주실 수 있으신가요?
![image](https://github.com/wlsdml1114/diff-svc/assets/135576360/0416d0c4-6b3c-47cb-a49d-da923f4fe820)
번거롭게해드려 죄송합니다

**Comment by popop098** [comment]
보니 아나콘다가 D드라이브에 설치되어있는것같습니다.
그러나 ffmpeg는 C드라이브에 있어 아나콘다가 ffmpeg를 찾지못하는것같습니다.
둘중하나를 동일한 드라이브에 위치시켜보세요

**Comment by cswgogo49** [comment]
> 보니 아나콘다가 D드라이브에 설치되어있는것같습니다. 그러나 ffmpeg는 C드라이브에 있어 아나콘다가 ffmpeg를 찾지못하는것같습니다. 둘중하나를 동일한 드라이브에 위치시켜보세요

옮겨봤는데도 계속 오류가 나네요...

**Comment by popop098** [comment]
그러면 ffmpeg.exe를 diff-svc-main폴더 안에 두고 해보세요

**Comment by wlsdml1114** [comment]
cmd창을 열고 그냥 ffmpeg만 한번 쳐보실래요?

**Comment by Ren-deRing** [comment]
anaconda prompt를 열고 ffmpeg를 입력해 보세요

**Comment by cswgogo49** [comment]
(base) D:\diff-svc-main>ffmpeg
ffmpeg version 2023-05-31-git-baa9fccf8d-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58. 12.100 / 58. 12.100
  libavcodec     60. 16.100 / 60. 16.100
  libavformat    60.  5.100 / 60.  5.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.101 /  9.  8.101
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

이렇게 나옵니다

**Comment by cswgogo49** [comment]
(diff-svc) C:\diff-svc-main>python sep_wav.py
mp4 to wav 변환 작업 중...: 100%|████████████████████████████████████████████████████████████████| 2/2 [00:00<?, ?it/s]
노멀라이징 작업 중...:   0%|                                                                     | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "C:\diff-svc-main\sep_wav.py", line 285, in <module>
    main(
  File "C:\diff-svc-main\sep_wav.py", line 172, in main
    audio_norm(filepath, out_filepath, use_preprocessing)
  File "C:\diff-svc-main\sep_wav.py", line 105, in audio_norm
    rawsound = AudioSegment.from_file(input_filepath, format=ext)
  File "C:\Users\cswgo\anaconda3\envs\diff-svc\lib\site-packages\pydub\audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 2023-05-31-git-baa9fccf8d-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58. 12.100 / 58. 12.100
  libavcodec     60. 16.100 / 60. 16.100
  libavformat    60.  5.100 / 60.  5.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.101 /  9.  8.101
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
[wav @ 000001d5db592c80] invalid start code riff in RIFF header
[in#0 @ 000001d5db592ac0] Error opening input: Invalid data found when processing input
 ffmpeg입력후에 python sep_wav.py입력하니 이렇게 나옵니다

**Comment by MoorDev** [comment]
파일 인식불가
Mp4파일 혹은 wav파일을 인식하지 못해 생긴문제입니다
경로에 한글이 있을때 이런일이 가끔생기거나 파일이 엉뚱한곳에 있을때 생기는 경우입니다

**Comment by cswgogo49** [comment]
> 파일 인식불가 Mp4파일 혹은 wav파일을 인식하지 못해 생긴문제입니다 경로에 한글이 있을때 이런일이 가끔생기거나 파일이 엉뚱한곳에 있을때 생기는 경우입니다

감사합니다 혹시나해서 파일을 좀 잘라서 넣으니까 되더라구요 너무 길어서 생긴 문제였나봅니다
