### ISSUE TITLE
    assert outputs.is_cuda or outputs.device.type == 'xla' 라는 오류가 발생합니다.

### ISSUE THREAD

**Issue by SJB7777** [wlsdml1114/diff-svc#63]
python run.py --config training/config.yaml --exp_name test --reset를 진행하던 도중

    assert outputs.is_cuda or outputs.device.type == 'xla'
AssertionError
Epoch 1: : 0batch [00:16, ?batch/s]
해당 오류가 발생했습니다. 해결방법이 있을까요

**Comment by SJB7777** [comment]
해결됐습니다. set CUDA_VISIBLE_DEVICES=0가 누락됐었네요

**Comment by MoorDev** [comment]
의외로 간단한 오류였군요 다행입니다
사용한 드라이버 버전을 알 수 있을까요?

**Comment by SJB7777** [comment]
NVIDIA GTX 1060에 드라이버 버전 31.0.15.3625입니다
