### ISSUE TITLE
binarize과정에서 오류가납니다..

### ISSUE THREAD

**Issue by schxo99** [wlsdml1114/diff-svc#64]
Skip item (Torch not compiled with CUDA enabled). item_name: data\test\b41-001.wav, wav_fn: data\test\b41-001.wav
 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 122/123 [01:00<00:00,  2.15it/s]| Skip item (Torch not compiled with CUDA enabled). item_name: data\test\b41-000.wav, wav_fn: data\test\b41-000.wav
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 123/123 [01:00<00:00,  2.02it/s]
Traceback (most recent call last):
  File "preprocessing/binarize.py", line 22, in <module>
    binarize()
  File "preprocessing/binarize.py", line 17, in binarize
    binarizer_cls().process()
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\preprocessing\..\preprocessing\base_binarizer.py", line 137, in process
    self.process_data_split('train')
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\preprocessing\..\preprocessing\base_binarizer.py", line 175, in process_data_split
    spec_max=np.max(spec_max,0)
  File "<__array_function__ internals>", line 200, in amax
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\fromnumeric.py", line 2820, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
뭐가 문제인지 알려주시면 감사하겠습니다 ..ㅠ

**Comment by Ren-deRing** [comment]
Pytorch를 제대로 설치하지 않으셨네요.
만약 pip install pytorch로 설치하셨다면

pip install torch==1.13.1 torchvision torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117

으로 설치해보세요.

**Comment by schxo99** [comment]
답변 감사합니다. 덕분에 해결했습니다!!

**Comment by schxo99** [comment]
PS C:\Users\me\Desktop\diff-svc\diff-svc-main> python run.py --config training/config_nsf.yaml --exp_name test --reset
| Hparams chains:  ['training/config_nsf.yaml']
| Hparams: 
K_step: 1000, accumulate_grad_batches: 1, audio_num_mel_bins: 128, audio_sample_rate: 44100, binarization_args: {'shuffle': False, 'with_align': True, 'with_f0': True, 'with_hubert': True, 'with_spk_embed': False, 'with_wav': False},
binarizer_cls: preprocessing.SVCpre.SVCBinarizer, binary_data_dir: data/binary/test, check_val_every_n_epoch: 10, choose_test_manually: False, clip_grad_norm: 1,
config_path: training/config_nsf.yaml, content_cond_steps: [], cwt_add_f0_loss: False, cwt_hidden_size: 128, cwt_layers: 2,
cwt_loss: l1, cwt_std_scale: 0.8, datasets: ['opencpop'], debug: False, dec_ffn_kernel_size: 9,
dec_layers: 4, decay_steps: 40000, decoder_type: fft, dict_dir: , diff_decoder_type: wavenet,
diff_loss_type: l2, dilation_cycle_length: 4, dropout: 0.1, ds_workers: 4, dur_enc_hidden_stride_kernel: ['0,2,3', '0,2,3', '0,1,3'],
dur_loss: mse, dur_predictor_kernel: 3, dur_predictor_layers: 5, enc_ffn_kernel_size: 9, enc_layers: 4,
encoder_K: 8, encoder_type: fft, endless_ds: False, f0_bin: 256, f0_max: 1100.0,
f0_min: 40.0, ffn_act: gelu, ffn_padding: SAME, fft_size: 2048, fmax: 16000,
fmin: 40, fs2_ckpt: , gaussian_start: True, gen_dir_name: , gen_tgt_spk_id: -1,
hidden_size: 256, hop_size: 512, hubert_gpu: True, hubert_path: checkpoints/hubert/hubert_soft.pt, infer: False,
keep_bins: 128, lambda_commit: 0.25, lambda_energy: 0.0, lambda_f0: 1.0, lambda_ph_dur: 0.3,
lambda_sent_dur: 1.0, lambda_uv: 1.0, lambda_word_dur: 1.0, load_ckpt: , log_interval: 100,
loud_norm: False, lr: 0.0008, max_beta: 0.02, max_epochs: 3000, max_eval_sentences: 1,
max_eval_tokens: 60000, max_frames: 42000, max_input_tokens: 60000, max_sentences: 10, max_tokens: 128000,
max_updates: 1000000, mel_loss: ssim:0.5|l1:0.5, mel_vmax: 1.5, mel_vmin: -6.0, min_level_db: -120,
no_fs2: True, norm_type: gn, num_ckpt_keep: 10, num_heads: 2, num_sanity_val_steps: 1,
num_spk: 1, num_test_samples: 0, num_valid_plots: 10, optimizer_adam_beta1: 0.9, optimizer_adam_beta2: 0.98,
out_wav_norm: False, pe_ckpt: checkpoints/0102_xiaoma_pe/model_ckpt_steps_60000.ckpt, pe_enable: False, perform_enhance: True, pitch_ar: False,
pitch_enc_hidden_stride_kernel: ['0,2,5', '0,2,5', '0,2,5'], pitch_extractor: parselmouth, pitch_loss: l2, pitch_norm: log, pitch_type: frame,
pndm_speedup: 10, pre_align_args: {'allow_no_txt': False, 'denoise': False, 'forced_align': 'mfa', 'txt_processor': 'zh_g2pM', 'use_sox': True, 'use_tone': False}, pre_align_cls: data_gen.singing.pre_align.SingingPreAlign, predictor_dropout: 0.5, predictor_grad: 0.1,
predictor_hidden: -1, predictor_kernel: 5, predictor_layers: 5, prenet_dropout: 0.5, prenet_hidden_size: 256,
pretrain_fs_ckpt: , processed_data_dir: xxx, profile_infer: False, raw_data_dir: data/test, ref_norm_layer: bn,
rel_pos: True, reset_phone_dict: True, residual_channels: 384, residual_layers: 20, save_best: False,
save_ckpt: True, save_codes: ['configs', 'modules', 'src', 'utils'], save_f0: True, save_gt: False, schedule_type: linear,
seed: 1234, sort_by_len: True, speaker_id: test, spec_max: [0.17769832909107208, 0.047376446425914764, 0.08477501571178436, 0.5036479830741882, 0.8853580355644226, 0.9447779655456543, 1.0005089044570923, 0.8345036506652832, 0.954767107963562, 1.0521939992904663, 0.9582710266113281, 0.9329121708869934, 0.9655966758728027, 0.9605810046195984, 0.9313068985939026, 1.0047392845153809, 0.9357585906982422, 0.8975078463554382, 0.9468656182289124, 0.9102059602737427, 0.872938334941864, 0.9026805758476257, 0.874439537525177, 0.8754749894142151, 0.9334968328475952, 0.9128067493438721, 0.7716197371482849, 0.8702632188796997, 0.8732779026031494, 0.921683132648468, 0.8425841927528381, 0.8866807818412781, 0.9284879565238953, 0.8770304918289185, 0.8666762709617615, 0.8386703133583069, 0.8818226456642151, 0.7923020720481873, 0.8751997351646423, 0.8326390981674194, 0.7749154567718506, 0.9362691640853882, 0.8156308531761169, 0.8458722233772278, 0.7519481778144836, 0.7699388265609741, 0.8115906715393066, 0.84813392162323, 0.7879219055175781, 0.8144434094429016, 0.8517191410064697, 0.8361592292785645, 0.8340405821800232, 0.7950232625007629, 0.7914908528327942, 0.6941058039665222, 0.7691239714622498, 0.6013504862785339, 0.5938386917114258, 0.6415841579437256, 0.5197851657867432, 0.5276553630828857, 0.5624308586120605, 0.48317617177963257, 0.4601943790912628, 0.3921191394329071, 0.4236898124217987, 0.43681785464286804, 0.41957464814186096, 0.3224891722202301, 0.2402532696723938, 0.28687071800231934, 0.17943476140499115, 0.16016076505184174, 0.16794216632843018, 0.14574646949768066, 0.17420169711112976, 0.14681068062782288, 0.09556535631418228, 0.14144371449947357, 0.061940934509038925, -0.016348643228411674, -0.17234620451927185, -0.17310228943824768, -0.08954241126775742, -0.29950469732284546, -0.28541114926338196, -0.2857770621776581, -0.30354368686676025, -0.38171103596687317, -0.3769735097885132, -0.45935365557670593, -0.40485477447509766, -0.46552568674087524, -0.36839789152145386, -0.3975342810153961, -0.5263907313346863, -0.5170790553092957, -0.5546187162399292, -0.5729273557662964, -0.6551704406738281, -0.6959905624389648, -0.4632129669189453, -0.6525623798370361, -0.5837680697441101, -0.7080055475234985, -0.45747795701026917, -0.6469612717628479, -0.7584559321403503, -0.6725834012031555, -0.8046972751617432, -0.7883543968200684, -0.753463864326477, -0.7106937766075134, -0.8671743273735046, -0.8549013733863831, -0.8177124857902527, -0.8866837024688721, -0.8947250247001648, -0.9512690305709839, -0.8608721494674683, -0.9060350060462952, -0.8812395930290222, -0.8444207310676575, -0.9024598002433777, -0.9487751722335815, -1.020869255065918, -1.1142017841339111], spec_min: [-4.999371528625488, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102],
spk_cond_steps: [], stop_token_weight: 5.0, task_cls: training.task.SVC_task.SVCTask, test_ids: [], test_input_dir: , 
test_num: 0, test_prefixes: ['test'], test_set_name: test, timesteps: 1000, train_set_name: train,
use_amp: True, use_crepe: True, use_denoise: False, use_energy_embed: False, use_gt_dur: False,
use_gt_f0: False, use_midi: False, use_nsf: True, use_pitch_embed: True, use_pos_embed: True,
use_spk_embed: False, use_spk_id: False, use_split_spk_id: False, use_uv: False, use_var_enc: False,
use_vec: False, val_check_interval: 2000, valid_num: 0, valid_set_name: valid, validate: False,
vocoder: network.vocoders.nsf_hifigan.NsfHifiGAN, vocoder_ckpt: checkpoints/nsf_hifigan/model, warmup_updates: 2000, wav2spec_eps: 1e-6, weight_decay: 0,
win_size: 2048, work_dir: checkpoints/test,
| Mel losses: {'ssim': 0.5, 'l1': 0.5}
| Load HifiGAN:  checkpoints/nsf_hifigan/model
Removing weight norm...
| model Trainable Parameters: 33.709M
sample time step: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:48<00:00,  2.06it/s]
sample time step: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:48<00:00,  2.05it/s]
==============
 valid results: {'total_loss': 0.9993, 'mel': 0.9993}
==============

Epoch 1: : 0batch [00:00, ?batch/s]Traceback (most recent call last):
  File "run.py", line 15, in <module>
    run_task()
  File "run.py", line 11, in run_task
    task_cls.start()
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\training\task\base_task.py", line 236, in start
    trainer.fit(task)
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\utils\pl_utils.py", line 500, in fit
    self.run_pretrain_routine(model)
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\utils\pl_utils.py", line 593, in run_pretrain_routine
    self.train()
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\utils\pl_utils.py", line 1369, in train
    self.run_training_epoch()
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\utils\pl_utils.py", line 1403, in run_training_epoch
    output = self.run_training_batch(batch, batch_idx)
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\utils\pl_utils.py", line 1529, in run_training_batch
    loss = optimizer_closure()
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\utils\pl_utils.py", line 1510, in optimizer_closure
    self.scaler.scale(closure_loss).backward()
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 164, in scale
    assert outputs.is_cuda or outputs.device.type == 'xla'
AssertionError
Epoch 1: : 0batch [00:09, ?batch/s]

혹시 이부분은 어떻게 해결해야하는지 여쭤봐도 될까요?

**Comment by Ren-deRing** [comment]
nsf_hifigan을 설치하지 않으셨네요.

**Comment by schxo99** [comment]
![image](https://github.com/wlsdml1114/diff-svc/assets/94772918/e26ac4f5-1a3d-417a-bb6f-ab49f135af45)
| Hparams chains:  ['training/config_nsf.yaml']
| Hparams: 
K_step: 1000, accumulate_grad_batches: 1, audio_num_mel_bins: 128, audio_sample_rate: 44100, binarization_args: {'shuffle': False, 'with_align': True, 'with_f0': True, 'with_hubert': True, 'with_spk_embed': False, 'with_wav': False},
binarizer_cls: preprocessing.SVCpre.SVCBinarizer, binary_data_dir: data/binary/test, check_val_every_n_epoch: 10, choose_test_manually: False, clip_grad_norm: 1,
config_path: training/config_nsf.yaml, content_cond_steps: [], cwt_add_f0_loss: False, cwt_hidden_size: 128, cwt_layers: 2,
cwt_loss: l1, cwt_std_scale: 0.8, datasets: ['opencpop'], debug: False, dec_ffn_kernel_size: 9,
dec_layers: 4, decay_steps: 40000, decoder_type: fft, dict_dir: , diff_decoder_type: wavenet,
diff_loss_type: l2, dilation_cycle_length: 4, dropout: 0.1, ds_workers: 4, dur_enc_hidden_stride_kernel: ['0,2,3', '0,2,3', '0,1,3'],
dur_loss: mse, dur_predictor_kernel: 3, dur_predictor_layers: 5, enc_ffn_kernel_size: 9, enc_layers: 4,
encoder_K: 8, encoder_type: fft, endless_ds: False, f0_bin: 256, f0_max: 1100.0,
f0_min: 40.0, ffn_act: gelu, ffn_padding: SAME, fft_size: 2048, fmax: 16000,
fmin: 40, fs2_ckpt: , gaussian_start: True, gen_dir_name: , gen_tgt_spk_id: -1,
hidden_size: 256, hop_size: 512, hubert_gpu: True, hubert_path: checkpoints/hubert/hubert_soft.pt, infer: False,
keep_bins: 128, lambda_commit: 0.25, lambda_energy: 0.0, lambda_f0: 1.0, lambda_ph_dur: 0.3,
lambda_sent_dur: 1.0, lambda_uv: 1.0, lambda_word_dur: 1.0, load_ckpt: , log_interval: 100,
loud_norm: False, lr: 0.0008, max_beta: 0.02, max_epochs: 3000, max_eval_sentences: 1,
max_eval_tokens: 60000, max_frames: 42000, max_input_tokens: 60000, max_sentences: 10, max_tokens: 128000,
max_updates: 1000000, mel_loss: ssim:0.5|l1:0.5, mel_vmax: 1.5, mel_vmin: -6.0, min_level_db: -120,
no_fs2: True, norm_type: gn, num_ckpt_keep: 10, num_heads: 2, num_sanity_val_steps: 1,
num_spk: 1, num_test_samples: 0, num_valid_plots: 10, optimizer_adam_beta1: 0.9, optimizer_adam_beta2: 0.98,
out_wav_norm: False, pe_ckpt: checkpoints/0102_xiaoma_pe/model_ckpt_steps_60000.ckpt, pe_enable: False, perform_enhance: True, pitch_ar: False,
pitch_enc_hidden_stride_kernel: ['0,2,5', '0,2,5', '0,2,5'], pitch_extractor: parselmouth, pitch_loss: l2, pitch_norm: log, pitch_type: frame,
pndm_speedup: 10, pre_align_args: {'allow_no_txt': False, 'denoise': False, 'forced_align': 'mfa', 'txt_processor': 'zh_g2pM', 'use_sox': True, 'use_tone': False}, pre_align_cls: data_gen.singing.pre_align.SingingPreAlign, predictor_dropout: 0.5, predictor_grad: 0.1,
predictor_hidden: -1, predictor_kernel: 5, predictor_layers: 5, prenet_dropout: 0.5, prenet_hidden_size: 256,
pretrain_fs_ckpt: , processed_data_dir: xxx, profile_infer: False, raw_data_dir: data/test, ref_norm_layer: bn,
rel_pos: True, reset_phone_dict: True, residual_channels: 384, residual_layers: 20, save_best: False,
save_ckpt: True, save_codes: ['configs', 'modules', 'src', 'utils'], save_f0: True, save_gt: False, schedule_type: linear,
seed: 1234, sort_by_len: True, speaker_id: test, spec_max: [0.17769832909107208, 0.047376446425914764, 0.08477501571178436, 0.5036479830741882, 0.8853580355644226, 0.9447779655456543, 1.0005089044570923, 0.8345036506652832, 0.954767107963562, 1.0521939992904663, 0.9582710266113281, 0.9329121708869934, 0.9655966758728027, 0.9605810046195984, 0.9313068985939026, 1.0047392845153809, 0.9357585906982422, 0.8975078463554382, 0.9468656182289124, 0.9102059602737427, 0.872938334941864, 0.9026805758476257, 0.874439537525177, 0.8754749894142151, 0.9334968328475952, 0.9128067493438721, 0.7716197371482849, 0.8702632188796997, 0.8732779026031494, 0.921683132648468, 0.8425841927528381, 0.8866807818412781, 0.9284879565238953, 0.8770304918289185, 0.8666762709617615, 0.8386703133583069, 0.8818226456642151, 0.7923020720481873, 0.8751997351646423, 0.8326390981674194, 0.7749154567718506, 0.9362691640853882, 0.8156308531761169, 0.8458722233772278, 0.7519481778144836, 0.7699388265609741, 0.8115906715393066, 0.84813392162323, 0.7879219055175781, 0.8144434094429016, 0.8517191410064697, 0.8361592292785645, 0.8340405821800232, 0.7950232625007629, 0.7914908528327942, 0.6941058039665222, 0.7691239714622498, 0.6013504862785339, 0.5938386917114258, 0.6415841579437256, 0.5197851657867432, 0.5276553630828857, 0.5624308586120605, 0.48317617177963257, 0.4601943790912628, 0.3921191394329071, 0.4236898124217987, 0.43681785464286804, 0.41957464814186096, 0.3224891722202301, 0.2402532696723938, 0.28687071800231934, 0.17943476140499115, 0.16016076505184174, 0.16794216632843018, 0.14574646949768066, 0.17420169711112976, 0.14681068062782288, 0.09556535631418228, 0.14144371449947357, 0.061940934509038925, -0.016348643228411674, -0.17234620451927185, -0.17310228943824768, -0.08954241126775742, -0.29950469732284546, -0.28541114926338196, -0.2857770621776581, -0.30354368686676025, -0.38171103596687317, -0.3769735097885132, -0.45935365557670593, -0.40485477447509766, -0.46552568674087524, -0.36839789152145386, -0.3975342810153961, -0.5263907313346863, -0.5170790553092957, -0.5546187162399292, -0.5729273557662964, -0.6551704406738281, -0.6959905624389648, -0.4632129669189453, -0.6525623798370361, -0.5837680697441101, -0.7080055475234985, -0.45747795701026917, -0.6469612717628479, -0.7584559321403503, -0.6725834012031555, -0.8046972751617432, -0.7883543968200684, -0.753463864326477, -0.7106937766075134, -0.8671743273735046, -0.8549013733863831, -0.8177124857902527, -0.8866837024688721, -0.8947250247001648, -0.9512690305709839, -0.8608721494674683, -0.9060350060462952, -0.8812395930290222, -0.8444207310676575, -0.9024598002433777, -0.9487751722335815, -1.020869255065918, -1.1142017841339111], spec_min: [-4.999371528625488, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, 
-4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102, -4.999994277954102],
spk_cond_steps: [], stop_token_weight: 5.0, task_cls: training.task.SVC_task.SVCTask, test_ids: [], test_input_dir: ,
test_num: 0, test_prefixes: ['test'], test_set_name: test, timesteps: 1000, train_set_name: train,
use_amp: True, use_crepe: True, use_denoise: False, use_energy_embed: False, use_gt_dur: False,
use_gt_f0: False, use_midi: False, use_nsf: True, use_pitch_embed: True, use_pos_embed: True,
use_spk_embed: False, use_spk_id: False, use_split_spk_id: False, use_uv: False, use_var_enc: False,
use_vec: False, val_check_interval: 2000, valid_num: 0, valid_set_name: valid, validate: False,
vocoder: network.vocoders.nsf_hifigan.NsfHifiGAN, vocoder_ckpt: checkpoints/nsf_hifigan/model, warmup_updates: 2000, wav2spec_eps: 1e-6, weight_decay: 0,
win_size: 2048, work_dir: checkpoints/test,
| Mel losses: {'ssim': 0.5, 'l1': 0.5}
| Load HifiGAN:  checkpoints/nsf_hifigan/model
Removing weight norm...
| model Trainable Parameters: 33.709M
sample time step: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:42<00:00,  2.35it/s] 
sample time step: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:42<00:00,  2.29it/s] 
==============
 valid results: {'total_loss': 1.0035, 'mel': 1.0035}
==============

Epoch 1: : 0batch [00:00, ?batch/s]Traceback (most recent call last):
  File "run.py", line 15, in <module>
    run_task()
  File "run.py", line 11, in run_task
    task_cls.start()
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\training\task\base_task.py", line 236, in start
    trainer.fit(task)
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\utils\pl_utils.py", line 500, in fit
    self.run_pretrain_routine(model)
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\utils\pl_utils.py", line 593, in run_pretrain_routine
    self.train()
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\utils\pl_utils.py", line 1369, in train
    self.run_training_epoch()
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\utils\pl_utils.py", line 1403, in run_training_epoch
    output = self.run_training_batch(batch, batch_idx)
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\utils\pl_utils.py", line 1529, in run_training_batch
    loss = optimizer_closure()
  File "C:\Users\me\Desktop\diff-svc\diff-svc-main\utils\pl_utils.py", line 1510, in optimizer_closure
    self.scaler.scale(closure_loss).backward()
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 164, in scale
    assert outputs.is_cuda or outputs.device.type == 'xla'
AssertionError
Epoch 1: : 0batch [00:08, ?batch/s]
checkpoints파일구조입니다. nsf_hifigan안의 파일들들을 checkpoints하위폴더로 옮겨서도 해봈는데 같은 오류가 나타납니다..ㅠ

**Comment by Ren-deRing** [comment]
set CUDA_VISIBLE_DEVICES=0 명령어를 입력하셨나요?

**Comment by schxo99** [comment]
네 ㅠㅠ

**Comment by schxo99** [comment]
해결했습니다~ 세팅부터 처음부터 다시하니 되네요
