### ISSUE TITLE
초보라서

### ISSUE THREAD

**Issue by thuglife114** [wlsdml1114/diff-svc#7]
유투브 보면서 따라했는데, 거의 다 이상없이 왔는데
infer.py를 메모장으로 열고 님이 위에 설정한 configure에 맞게 수정해야함"을 하기위해  diff-svc-main\checkpoints\test 폴더에 갔는데 왜 *.ckpt 파일들이 업을까요?
"exp_name을 위에 설정한 이름으로 바꿔주면 된다"
이것도 잘 이해가 안가요 ㅠㅠ

**Comment by MoorDev** [comment]
아직 충분히 학습 되지 않아 모델이 만들어지지 않은것입니다
2000step 당 하나씩 ckpt모델이 만들어지며 60000step부터 사람이 들을 수 있는 수준이 되고 (10 max senetence기준 하지만 그래도 계속 웅웅대는 소리가 들림) 상황에 따라 더 많은 학습이 필요하거나 더 많은 데이터 투입이 필요합니다.

제 경우에는 지금 80000step정도 됐는데 이틀걸렸습니다. 그런데 아직도 total loss값이 0.2입니다. 몇배는 더 낮아져야 쓸만한 목소리가 나올듯 합니다

더 많이 더 오래 학습하세요

**Comment by thuglife114** [comment]
답변 감사합니다
그래서 음성 wav파일을 더 준비하여 해볼게요

잘 하시면, 연락처 부탁드려도 될까요? 통화하면서 배우고 싶습니다

**Comment by MoorDev** [comment]
librosa가 설치가 안 된겁니다
pip install librosa

그런데 이전에 학습이 진행됐다고 하셨죠? 그럼 conda activate diff-svc 이거 하신건지 확인해보세요. 아나콘다에서 아마 앞에 (base) 이렇게 적혀있다면 (diff-svc)로 바뀌었는지 확인이 필요할겁니다.

그리고 저 역시 회사에서 몰래 하는 중이라 조금 힘들겁니다. 대신 여기 저장소 주인님이 도와주실수도 있을겁니다

**Comment by thuglife114** [comment]
답변 감사합니다

질문이 있는데 아시면 알려주세요 ㅠㅠ

A라는 노래를 B의 목소리로 만들려고 한다고 치면
B의 목소리를 preprocess 폴더에 넣은다음 python하여 쪼개서
유투브대로 data 폴더로 옮겨서 하는거잖아요

그렇다면 A라는 원본 샘플은 어디에다가 넣어야하나요?

**Comment by wlsdml1114** [comment]
https://github.com/wlsdml1114/diff-svc#%EB%AA%A8%EB%8D%B8-%ED%95%99%EC%8A%B5-%EB%B0%8F-%EA%B2%B0%EA%B3%BC%EB%AC%BC-%EB%BD%91%EA%B8%B0
2번의 대괄호 안에 들어가는 파일이름이 A라는 원본 샘플이 됩니다.

raw폴더 안에 넣고 원본 샘플의 파일명을 대괄호 안에 넣으면 됩니다.

**Comment by thuglife114** [comment]
아 감사합니다
계속 질문이 생기는되요, 그렇다면 원본 샘플이 어떤 음악이라고 하면
그 음악의 배경음악을 지우고 어떻게 노래한 목소리만 얻을수 있을까요?

**Comment by wlsdml1114** [comment]
온라인툴도 많구요
python으로는 demucs를 이용하시면 편합니다. (demucs가 현재 프로젝트에도 사용되고 있어서 약간만 수정하면 사용하실 수 있긴 합니다.)
코딩에 익숙하지 않으신분이면 온라인으로 목소리만 추출해서 사용하시는것도 추천합니다.

**Comment by thuglife114** [comment]
너무 감사합니다
온라인툴 검색해보겠습니다
