### ISSUE TITLE
학습은 얼마나 해야할까요?

### ISSUE THREAD

**Issue by thuglife114** [wlsdml1114/diff-svc#9]
이걸 스텝이라고 하나요?

저절로 끝나진 않는거 같은데, 얼마정도가 적당한가요?

현재 30만스텝했네요

**Comment by wlsdml1114** [comment]
보통 10만스텝 내외에서 중단하는 것 같습니다.
데이터셋과 cofigure에 따라 다르기때문에 딱 얼마인지는 말씀드리기 어렵습니다만, loss가 어느정도 수렴해서 더 이상 줄지 않으면 학습을 그만해도 됩니다.

**Comment by thuglife114** [comment]
감사합니다 그만 해도 되겠네요
